### ISSUE TITLE
Feature request: passing all module variables in another module

### ISSUE THREAD

**Issue by Kroid** [sass/dart-sass#1003]
What do you think about passing all module variables in another module?

For example, something like that:

```scss
//_mixins.scss
$background-color: black !default;
$color: red !default;
$font-size: 12px !default;

@mixin demo {
  background-color: $background-color;
  color: $color;
  font-size: $font-size;
}
```

```scss
//_myvars.scss
$color: blue !default;
$font-size: 18px !default;
```

```scss
//style.scss
@use "myvars";
@use "mixins" with (myvars.*)

h1 {
  @include mixins.demo;
}
```

will compile to:

```css
h1 {
  background-color: black;
  color: blue;
  font-size: 18px;
}
```
