### ISSUE TITLE
Extra whitespace after "#{}" interpolation

### ISSUE THREAD

**Issue by hsrepos** [sass/dart-sass#1008]
Hi there,

I'm currently experiencing an issue when using interpolation. Here is an example:

`
@function round-width($i) {
  $width: floor(100 * $i * 100 / $grid-columns) / 100;
  @return $width#{"%"};
}
`

Anytime I make use of this function the compiled sass file displays as follows (example):

width: 33.33 %;

The additional white space emitted  is breaking the entire output...

Any ideas?

**Comment by pat270** [comment]
`#{$width}#{"%"}` should work

**Comment by hsrepos** [comment]
@pat270 do you mind explaining the difference between the way I had it originally and the way you suggested (btw your comment solved the issue)...

**Comment by hsrepos** [comment]
Thank you for solving my issue, appreciate the prompt response.

**Comment by hsrepos** [comment]
Yeah, I had trouble getting node-sass running with my current environment. Spotted that issue yesterday but trying to stick to the dart implementation unless I have to switch. Thanks for the work around. Very helpful.

**Comment by Awjin** [comment]
To provide more context here, Sass treats two expressions that are next each other as a space-separated list. Assuming `$width: 50`, the following—

```
a {
  b: $width$width;
}
```

evalutes to a space-separated list of numbers—

```
a {
  b: 50 50;
}
```
 The same applies to `$width#{$width}` and `#{$width}$width` since `$width` is an expression.

In `#{$width}#{$width}`, however, `#{$width}` interpolates to an unquoted string, so the result is two unquoted strings next to each other. This evaluates to one long unquoted string, `5050`.

All that being said, I recommend not using interpolation for numbers. Instead, use Sass's built in unit arithmetic:

```scss
@function round-width($i) {
  $width: floor(100% * $i * 100 / $grid-columns) / 100;
  @return $width;
}

or

@function round-width($i) {
  $width: floor(100 * $i * 100 / $grid-columns) / 100;
  @return $width * 1%;
}
```
