### ISSUE TITLE
Fails to parse escaped @else

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1011]
The below SCSS fails to parse using `dart-sass`
```scss
@if false {}

@\65lse {
  a {
    color: red;
  }
}
```
with the error
```scss
Error: This at-rule is not allowed here.
  ╷
3 │ @\65lse {
  │ ^^^^^^^^
  ╵
  foo.scss 3:1  root stylesheet
```
```
dart-sass --version
1.26.3
```

<br/>

`sassc` does not fail, but fails to recognize the escape,
```scss
@\65lse {
  a {
    color: red; } }
```

```
sassc --version
sassc: [NA]
libsass: [NA]
sass2scss: 1.1.1
sass: 3.5
```
(`sassc` was built from source using the most recent commit, https://github.com/sass/sassc/commit/3e73baee972f5f46f4ce1a7a84e0efd3c3563c30, and a very recent libsass commit)

<br>

An escaped version of `@if` does parse and evaluate correctly,
```scss
@\69 f true {
  a {
    color: red;
  }
}
```
(though again libsass does not recognize the escape)
