### ISSUE TITLE
Missing `;base64` in Embedded Source Map 

### ISSUE THREAD

**Issue by sntran** [sass/dart-sass#1022]
## Steps to Reproduce

```scss
body {
  box-sizing: border-box;
}
```

```shell
npx sass --embed-source-map test.scss
```

## Expected Output

```css
body {
  box-sizing: border-box;
}

/*# sourceMappingURL=data:application/json;charset=utf-8;base64,%7B%22version%22:3,%22sourceRoot%22:%22%22,%22sources%22:%5B%22file:///Users/sntran/Projects/@brandextract/gaia/src/css/test.scss%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA;EACE%22%7D */
```

## Actual Output

```css
body {
  box-sizing: border-box;
}

/*# sourceMappingURL=data:application/json;charset=utf-8,%7B%22version%22:3,%22sourceRoot%22:%22%22,%22sources%22:%5B%22file:///Users/sntran/Projects/@brandextract/gaia/src/css/test.scss%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA;EACE%22%7D */
```

## Environment

```shell
$ node --version
v12.14.1
$ npx sass --version
1.26.8 compiled with dart2js 2.8.4
```

## Notes

The current embedded source map output, when sent to `postcss` for further processing, fails `postcss` with the following error:

```shell
Error: Unsupported source map encoding charset=utf-8
```

The error comes from [this function](https://github.com/postcss/postcss/blob/cf83abc98bb85e3dc536bbc23ec9f83e9aaaa154/lib/previous-map.es6#L93-L108), which fails to test against just `data:application/json;charset=utf-8,`
