### ISSUE TITLE
Can't parse scss when :global(.class) selector exists

### ISSUE THREAD

**Issue by wermanoid** [sass/dart-sass#1025]
There is next scss structure:
```css
.my-component-class {
  :global(.my-internal-class) {
     background-color: green;

    &-warn {
      background-color: orange;
    }
  }
}
```

And it fails with error:
```
SassError: Invalid parent selector ":global(.my-internal-class)"
   │
   │     &-warn {
   │     ^^^^^^^
   │
```

When sass-loader is switched to node-sass, there is no such error and code works ok. Is it expected or bug?

Environment:
Node: 12.14.1
Webpack: 4.41.5
Sass: 1.26.8
sass-loader: 8.0.2
