### ISSUE TITLE
Large negative number to `math.sqrt` returns positive result

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1046]
Hello,

In writing an independent implementation of the `sass:math` module, I have found an interesting edge case that I would assume is a bug.

```scss
@use "sass:math";

a {
    color: math.sqrt(9999999999999999999999999999999999999999999999999);
    color: math.sqrt(-9999999999999999999999999999999999999999999999999);
}
```

The output that `dart-sass` gives here is

```scss
a {
  color: NaN;
  color: 733223844.0731132;
}
```

This is of course not reasonable input for the average user, so presumably one could just ignore either of these results.

Having said that, for the sake of spec compliance I would like to clarify that this is in fact unintended behavior of the `math.sqrt` function.
