### ISSUE TITLE
Custom functions with more than 6 parameters fail

### ISSUE THREAD

**Issue by rarous** [sass/dart-sass#1051]
Hi,

I'm in progress of migrating from `node-sass` to `dart-sass` and I found inconvenient incompatibility. We use custom functions to transform image URLs. Failing function has many optional parameters. I tried to narrow down the problem and end with this reproduction:

```
const sass = require("sass");
const result = sass.renderSync({
  data: `
    body {
      color: test(1, 2, 3, 4 , 5, 6, 7);
    }
  `,
  functions: {
    "test($a, $b, $c, $d, $e, $f, $g)": () => new sass.types.String("green")
  }
});
console.log(result.css.toString())
```

This will fail with following error:

```
Error: NoSuchMethodError: method not found: 'call'
Receiver: Instance of 'JavaScriptFunction'
Arguments: [Instance of 'SassNumber', Instance of 'SassNumber', Instance of 'SassNumber', Instance of 'SassNumber', Instance of 'SassNumber', Instance of 'SassNumber', Instance of 'SassNumber']
  ╷
3 │       color: test(1, 2, 3, 4 , 5, 6, 7);
  │              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

If you remove last parameter, it will work as expected.

**Comment by zaydek** [comment]
FWIW you might be able to use a variadic parameter to solve your problem.

This is an example in Sass:

```scss
@function thing($arr...) {
    $map: ();
	@each $v in $arr {
		$map: join($map, $v);
	}
	@return $map;
}

@each $v in thing(1, 2, 3) {
    .a-#{$v} {
        top: 0;
    }
}
```

```css
.a-1 {
  top: 0;
}

.a-2 {
  top: 0;
}

.a-3 {
  top: 0;
}
```

I haven’t tried it with the JS API but it might be worth a shot in the meantime.
