### ISSUE TITLE
Silently ignores errors in native CSS mixins

### ISSUE THREAD

**Issue by tony19** [sass/dart-sass#108]
`dart-sass` happily ignores garbage inside native CSS mixins such as the following:

*styles.scss*
```scss
$color: #4285f4;
:host {
  display: block;
  padding: 10px;
  --view1-card: {
    border: solid 1px #{$color};
    foo();k;lfajkf;
    fdjkfldajl
  };
}
```

*build.js*:
```javascript
const dartSass = require('dart-sass');
dartSass.render({file: 'styles.scss'}, (err: Error, result: Buffer) => {
  // ...
});
```

Running `styles.scss` through `build.js` results in no warnings or errors. The `result` contains the garbage as-is:

```css
:host {
  display: block;
  padding: 10px;
  --view1-card: {
    border: solid 1px #4285f4;
    foo();k;lfajkf;
    fdjkfldajl
  };
}
```

I expected to see an error.

### Environment

 * macOS Sierra 10.12
 * node 7.4.0
 * `dart-sass` 1.0.0-alpha.8
