### ISSUE TITLE
JS API: Support full error value

### ISSUE THREAD

**Issue by tony19** [sass/dart-sass#109]
When `dart-sass` detects an error in a `.scss` file, it invokes the callback with an `err` object that contains `message`, but there's no file/line info for correlation.

### Steps to reproduce

 1. Install `dart-sass` 1.0.0-alpha.8 with: `npm install dart-sass`
 2. Create a Gulp task that calls `dart-sass` like this:

```javascript
dartSass.render({file: file.path}, (err, result) => {
    if (err) {
      console.error('sass error', err);
    } else {
      file.contents = result.buffer;
    }
    cb(err, file);
});
```

 3. Pipe the following file to `dart-sass`:

*foo.scss:*
```scss
:host {
  display: block;
  padding: 10px;

  --view1-card: {
    'foo   /* intentionally unterminated string */
  }
}
```

### Expected result
The callback's `err` object included file and line info.

### Actual result
Only `message` (without file/line info) is provided in `err`. The `message` contains:

    Expected '.

### Environment
 * dart-sass 1.0.0-alpha.8
 * node 7.5.0
 * gulp 3.9.1
 * macOS Sierra 10.12
