### ISSUE TITLE
Proposal - Allow Custom Property Nesting 

### ISSUE THREAD

**Issue by jakob-e** [sass/dart-sass#1093]
**Extend property nesting to allow Custom Properties**

I know there is a lot to be considered when dealing with custom properties – why the following suggestion may not be as easy to implement as it looks 🤗. 

 
_SCSS:_
````SCSS
$color-h1: #cf649a;

@mixin h1 {
  font-size: 3rem;
  line-height: 1.15;
  color: #{$color-h1};  // interpolation probably required 
}

//  nested  
html {
  --h1: {
    @include h1;
  } 
} 

//  regular 
h1 {
  @include h1;
}

````
_CSS:_
````CSS
html {
  --h1-font-size: 3rem;
  --h1-line-height: 1.15;  
  --h1-color: #cf649a; 
}

h1 {
  font-size: 3rem;
  line-height: 1.15;
  color: #cf649a;
}
`````

**Comment by Awjin** [comment]
Sass does not support dynamically creating CSS custom properties. I would suggest [using interpolation](https://sass-lang.com/documentation/style-rules/declarations#custom-properties) to assign values to custom properties, either directly within the `html {}` style rule, or within a mixin.

**Comment by jakob-e** [comment]
**Did you read my proposal at all???**

**Comment by nex3** [comment]
@jakob-e Please re-read the [Sass Community Guidelines](https://sass-lang.com/community-guidelines). This was a very rude response, and not an appropriate way to communicate.

**Comment by Awjin** [comment]
There might be a way to achieve this by interpolating the custom property, to force it to be interpreted as SassScript:

```scss
@mixin h1 {
  font-size: 3rem;
  line-height: 1.15;
  color: #cf649a;
}

html {
  #{--h2}: {
    @include h1;
  } 
}
```

(Note this does not currently work in Dart Sass)

**Comment by jakob-e** [comment]
I apologize 😳💐

**Comment by jakob-e** [comment]
Would it be possible for Sass to add special treatment to the combination `: { }`
similar to the rule for interpolation `#{ }`

A simpler example (without the mixin confusion)
````SCSS
// SCSS
.regular-property {
  background: {
    color: red;
  }
}
// CSS
.regular-property {
  background-color: red;
}

// SCSS
.custom-property {
   --background: {
      color: red;
   }
}
// CSS
.custom-property {
  --background-color: red;
}

````
