### ISSUE TITLE
Compiling incomplete output when use ":root .className"

### ISSUE THREAD

**Issue by serkon** [sass/dart-sass#1112]
Hi, I tried to compile below code but it not give export as expected.

```scss
$sizes: small medium large; 

%size {
  @each $item in $sizes {
    &-#{$item}, &.#{$item} {
      content: $item;
    }
  }
}

:root {
  @each $item in $sizes {
    .#{$item} {
      @extend %size-#{$item};
    }
  }
}

:root {
    .v-button {
        @extend %size;
    }
}
```

**Compiled output:**
```css
:root .small {
  content: small;
}
:root .medium {
  content: medium;
}
:root .large {
  content: large;
}
```

When use libSassv.3.5.5 it was compile as expected. But with DartSass v.1.26.11 compile incomplete.

**Exptected output:** 

```css
:root .small, :root .small.v-button {
  content: small;
}

:root .medium, :root .medium.v-button {
  content: medium;
}

:root .large, :root .large.v-button {
  content: large;
}
```

Can anyone offer me some support? 
I have to use DartSass for compiling.

Gist url: https://gist.github.com/serkon/d81c919dbaa4b4e5bcbcd8d717dbb5e2
Please try: https://www.sassmeister.com
