### ISSUE TITLE
Nested selector results in an incorrect extra comma-separated selector in CSS.

### ISSUE THREAD

**Issue by viktor-wolf** [sass/dart-sass#1122]
I apologize if the title doesn't really make sense, I wasn't sure how to best express what my problem is. I have encountered a strange issue where this code:

```scss
#page-topic {
  .BreadcrumbsSection {
    margin-top: 0;
    padding-top: 0;
    background: transparent;
  }

  .H2 {
    margin-top: 50px;
  }
}
```

Results in this CSS:

```css
#page-topic .BreadcrumbsSection {
  margin-top: 0;
  padding-top: 0;
  background: transparent;
}
#page-topic .H2, #page-topic .H2Link > .H2Link__Heading {
  margin-top: 50px;
}
```

The error is in the second selector where `#page-topic .H2Link > .H2Link__Heading` gets added for some mysterious reason, despite not being specified in the SCSS file. Those classes do exist elsewhere in my code.

I'm using SASS with gulp-sass 4.1.0 and dart-sass 1.25.0.
