### ISSUE TITLE
Sass variables are not resolved when assigned to CSS3 variables.

### ISSUE THREAD

**Issue by infacto** [sass/dart-sass#1140]
# Bug Report

**SCSS**
```scss
$my-opacity: 0.5;

.my-class {
  --opacity: $my-opacity;
  opacity: $my-opacity;
}
```

## Expected behavior.

**CSS**
```css
.my-class {
  --opacity: 0.5;
  opacity: 0.5;
}
```

## Current behavior.

**CSS**
```css
.my-class {
  --opacity: $my-opacity;
  opacity: 0.5;
}
```

Inspected by Chrome. The CSS3 variables holds the string `$my-opacity` and not the number `0.5`. Why? 

## Workaround

**SCSS**
```scss
$my-opacity: 0.5;

.my-class {
  --opacity: #{$my-opacity};
  opacity: $my-opacity;
}
```

But I don't understand why. Ok, `opacity` is a known property. Maybe the Sass compiler evaluates it. Anyway... If I want to hold a string I would quote it. Should I always use `#{...}` for variables? Should we change this? Is this a bug? ... 🤔 
This should work more like I expected. Variable `$...` should be always resolved. Someone who want's a string in this case should use quotes or other syntax for that. I expected that all Sass variables are resolved during compilation.
I see no reason we should not do this. But explain me please. 🙂 

## Versions
Using [Angular 11](https://github.com/angular/angular).
