### ISSUE TITLE
HWB color information not preserved

### ISSUE THREAD

**Issue by mgreter** [sass/dart-sass#1143]
It seems that dart-sass does not preserve color information and always uses clamped rgb color components.

```scss
@use 'sass:color';
test {
  a: color.whiteness(gray);
  b: color.whiteness(color.hwb(0, 50%, 0%));
  c: color.whiteness(color.hwb(0, 50%, 50%));
  d: color.whiteness(color.hwb(0, 70%, 70%));
}
```

This gives the following output:
```css
test {
  a: 50.1960784314%;
  b: 50.1960784314%;
  c: 50.1960784314%;
  d: 50.1960784314%;
}
```

I wonder if this is the desired behavior? Wouldn't it make sense to preserve the information as much as possible?
I'm currently preserving that info in libsass until when a conversion is really needed.
In order to support this better I would also like to add the possibility to pass a color to e.g. `rgba`, as in:

```scss
test {
  a: color.whiteness(color.rgba(color.hwb(0, 70%, 30%)));
}
```

This would trigger the conversion to rgb components. Still open question if we should round
the components to integers, I tend to prefer to preserve as much info as possible.
The `rgb(color)` function would probably reset the alpha channel to 100%.
With preserving the double precision the above would result in:

```css
test {
  a: 50%;
}
```

Hope that makes sense!
