### ISSUE TITLE
Support custom ext file.

### ISSUE THREAD

**Issue by liuweiGL** [sass/dart-sass#1148]
## Feature
Support custom ext file.

## Problem
`node-sass` work fine, but `dart-sass` get an error.

## Example
`test.wxss` file:
```css
.a {
  color: red;
}
```
`index.scss` file:
```scss
@import './test.wxss';

.b {
  color: blue;
}
```
## Result
node-sass:
![image](https://user-images.githubusercontent.com/21048878/99367546-0f140180-28f5-11eb-9f65-b1ee56f0f359.png)

dart-sass:
![image](https://user-images.githubusercontent.com/21048878/99367584-1c30f080-28f5-11eb-866c-d94ee4bf095f.png)
