### ISSUE TITLE
[Question] Is there a better technique for colocating classes?

### ISSUE THREAD

**Issue by zaydek** [sass/dart-sass#1152]
In Sass, even when you collocate rules (so there’s no line-break between them), the generated output prints a line-break between them (example 1).

What I’m wondering is if there’s a better way to get the desired behavior (example 2). I know I can use a clever `@at-root` trick to achieve the desired result, but I’m wondering if there’s a better way to do this?

Thank you!

**Example 1:**

```scss
.a {
	top: 0;
}
.b {
	top: 0;
}
// .a {
//   top: 0;
// }
// 
// .b {
//   top: 0;
// }
```

**Example 2:**

```scss
.a {
	top: 0;
	@at-root {
		.b {
			top: 0;
		}
	}
}
// .a {
//   top: 0;
// }
// .b {
//   top: 0;
// }
```
