### ISSUE TITLE
Multiline comment throws error

### ISSUE THREAD

**Issue by tuelsch** [sass/dart-sass#1170]
Multiline comments with `/* */` are being parsed to produce CSS output. But in the following case, this feature is either not working correctly or my use case is not supported - which would be rather frustrating.

I don't want to render the loop for a sec to test something. I comment it out. Sass throws an error.

```scss
$list: (1, 2, 3, 4, 5);
/*@each $n in $list {
    .i#{$n} {
        padding: 1px;
    }
}*/
```

```cmd
Error: Undefined variable.
  ╷
3 │     .i#{$n} {
  │         ^^
  ╵
```

Does sass just (try to) interpret the interpolation?
