### ISSUE TITLE
Support nesting import for css

### ISSUE THREAD

**Issue by xiaoxiangmoe** [sass/dart-sass#1192]
We have two file as below:

```css
/* _bar.css */
.spam {
    color: red;
}
```
```scss
/* _foo.scss */
.spam {
    color: red;
}
```

```js
// index.js
const sass = require('sass');

const result = sass.renderSync({file: "input.scss",});

console.log(result.css.toString())
```

```scss
// input.scss
.foo {
    @import './_foo.scss';
}

.bar {
    @import './_bar.css';
}
```

Then we run `node index.js` and it puts

```css
.foo {
  /* _foo.scss */
}
.foo .spam {
  color: red;
}

.bar {
  @import './_bar.css';
}
```

It shows that nesting import for scss files is well, but it is not working for css.
