### ISSUE TITLE
Different output with parent ampersand with %placeholder and with @mixin

### ISSUE THREAD

**Issue by nikistefanov** [sass/dart-sass#1194]
Hi SASS team,

I've hit one case with different outputs between `%placeholder` and `@mixin`, the placeholder way generates 2 selectors, while the mixin - only 1. Was wondering if this is expected. Here is the case.
```` css
%test-1 {
    .test-1 & {
        font-size: 1px;
    }
}

@mixin test-2 {
    .test-2 & {
        font-size: 2px;
    }
}

html {
    .button {
        .icon-1 {
            @extend %test-1;
        }
        
        .icon-2 {
            @include test-2;
        }
    }
}
````
This will be outputted as followed:
```` css
.test-1 html .button .icon-1, html .button .test-1 .icon-1 {
  font-size: 1px;
}

.test-2 html .button .icon-2 {
  font-size: 2px;
}
````

**Comment by jathak** [comment]
This is intentional. `@extend`ing a placeholder can produce similar output to a mixin in simple cases, but the way it works is actually really different.

Extension means that all elements that match the extending selector (that the `@extend` rule is inside) are styled the same way as the extended selector (in this case, `%test-1`).

To better reason about this, here's your extension example without the nesting (and with the mixin example omitted for clarity):
```scss
.test-1 %test-1 {
  font-size: 1px;
}

html .button .icon-1 {
  @extend %test-1;
}
```

The first block here means "all `%test-1` elements that are descendants of `.test-1` elements should have their `font-size` set to `1px`. The extension in the second block means that all `.icon-1` elements that are descendants of `.button` elements that are descendants of `html` elements should be styled as if they are `%test-1` elements.

Putting these two statements together, we want to set `font-size` to `1px` to all `.icon-1` elements that are _both_ descendants of `.test-1` elements _and_ descendants of `.button` elements that are descendants of `html` elements. The order here doesn't matter, so we end up with both `.test-1 html. button .icon-1` and `html .button .test-1 .icon-1`.
