### ISSUE TITLE
Issue with deep-merge() function

### ISSUE THREAD

**Issue by ivodolenc** [sass/dart-sass#1239]
Hi 👋 as stated in the official docs [here](https://sass-lang.com/documentation/modules/map#deep-merge), is `deep-merge()` function implemented in the official release?

Maybe I'm doing something wrong but I can't get this function to work properly?

Here is the official example from the docs:

```scss
$helvetica-light: (
  'weights': (
    'lightest': 100,
    'light': 300
  )
);

$helvetica-heavy: (
  'weights': (
    'medium': 500,
    'bold': 700
  )
);

$example: deep-merge($helvetica-light, $helvetica-heavy);

@debug $example;
```

Throws: `SassError: ("weights": ("lightest": 100, "light": 300)) isn't a valid CSS value.`

I tested same example with `map-merge()` and this works as expected:

```scss
// output: ("weights": ("medium": 500, "bold": 700))
```

But when I add custom [deep-merge()](https://github.com/sass/sass/pull/2836#issuecomment-612647102) function everything works properly:

```scss
@function deep-merge($maps...) {
  $merged: ();

  @each $map in $maps {
    @each $key, $val in $map {
      @if (type-of($val) == 'map') {
        $current: map-get($merged, $key);
        @if (type-of($current) == 'map') {
          $val: deep-merge($current, $val);
          $map: map-merge(
            $map,
            (
              $key: $val
            )
          );
        }
      }
    }
    $merged: map-merge($merged, $map);
  }

  @return $merged;
}

$helvetica-light: (
  'weights': (
    'lightest': 100,
    'light': 300
  )
);

$helvetica-heavy: (
  'weights': (
    'medium': 500,
    'bold': 700
  )
);

$example: deep-merge($helvetica-light, $helvetica-heavy);

@debug $example;

// output: ("weights": ("lightest": 100, "light": 300, "medium": 500, "bold": 700))
```
Please can someone take a look at this and give an opinion? Maybe I'm really doing something wrong here 😀 🤦‍♂️

Testing environment:

- `nuxt v2.15.2`
- `sass v1.32.6`
- `sass-loader v10.1.1`
- `fibers v5.0.0`

Also won't work in:

- `gulp v4.0.2`
- `gulp-dart-sass v1.0.2`
- `fibers v5.0.0`
