### ISSUE TITLE
Creating a theme with dart-sass

### ISSUE THREAD

**Issue by ivodolenc** [sass/dart-sass#1241]
I literally yesterday discover that the classic way of using `SASS` will be deprecated and that it will move to a "new" way (`@use`, `@forward` etc.).

This brings a lot of questions and requires investing extra time to re-learn the new usage (actually not a big deal).

Don’t get me wrong, this is not a critique nor do I mean anything bad about `SASS`. I’m just curious and wondering how I can create a theme in this new way like we’ve done so far.

I’ll give an example of what actually interests me.

Let’s say we have a theme with some default settings and we want to publish it to npm (something like a bootstrap, etc.). The theme must provide a way for users to customize it to their own needs. In the classic way (`@import`) this can be done with ease and is not a problem at all.

I want to mention that I created the theme in a classic way and that everything works perfectly. But according to this news of deprecation, I want to migrate to dart sass before I publish it.

So this is example where I stuck:

**main.scss**

```scss
@use 'base';
@use 'settings';
@use 'utils';
// ...
```

**settings/\_index.scss**

```scss
@forward 'functions';
@forward 'theme';
@forward 'breakpoints';
@forward 'spacing';
@forward 'colors';
// ...
```

**settings/\_theme.scss**

```scss
@use 'sass:map';

$theme: () !default;
$theme: map.deep-merge(
  (
    'breakpoints-unit': px,
    'map-clear': (),
    // ...
  ),
  $theme
);

// Gets values from theme map

@function theme($keys...) {
  $map: $theme;

  @each $key in $keys {
    $map: map-get($map, $key);
  }
  @return $map;
}
```

**settings/\_breakpoints.scss**

```scss
@use 'theme';
@use 'sass:map';

theme.$theme: map.deep-merge(
  (
    'breakpoints': (
      'sm': 500px,
      'md': 700px,
      'lg': 1000px,
      'xl': 1200px,
      'xxl': 1400px
    )
  ),
  theme.$theme
);
```

This works as expected, but when I tried to override theme defaults, values didn't updated in `$theme` map like it would be using the classic way.

```scss
$theme: (
  'breakpoints': (
    'sm': 300px,
    'md': 900px,
    'xxl': 1600px
  )
);

@use 'base';
@use 'settings';
@use 'utils';

@debug $theme;

// output:" (breakpoints": ("sm": 500px, "md": 700px, "lg": 1000px, "xl": 1200px, "xxl": 1400px))
```

Sorry for long post and hope someone will share a way how we can deal with this, so users can customize theme.

**Comment by ivodolenc** [comment]
Ok, after more searching and testing over the weekend, I think I've figured it out.

Migration requires additional configurations and perhaps a new structuring and naming system, but that’s not a big deal.

Here is an example:

**main.scss**

```scss
// This is the 'main' file that we later import from npm

@forward 'functions';
@forward 'base';
@forward 'config';
@forward 'theme';
@forward 'mixins';
@forward 'utils';
// ...
```

**theme/\_index.scss**

```scss
// This contains all theme settings

@use 'sass:map';

$theme: () !default;
$theme: map.deep-merge(
  (
    'breakpoints': (
      'sm': 500px,
      'md': 700px,
      'lg': 1000px,
      'xl': 1200px,
      'xxl': 1400px
    ),
    'colors': (
      'transparent': transparent,
      'current': currentColor,
      'black': rgba(#000, 1),
      'white': rgba(#fff, 1),
      'gray': (
        '50': rgba(#fafafa, 1),
        '100': rgba(#f5f5f5, 1),
        '200': rgba(#e5e5e5, 1),
        '300': rgba(#d4d4d4, 1),
        '400': rgba(#a3a3a3, 1),
        '500': rgba(#737373, 1),
        '600': rgba(#525252, 1),
        '700': rgba(#404040, 1),
        '800': rgba(#262626, 1),
        '900': rgba(#171717, 1)
      ),
      // ...
    )
  ),
  $theme
);

// Gets values from theme map
//
// example scss
//
// .element {
//   color: theme('colors', 'gray', '100');
//   background-color: theme('colors', 'black');
// }
//

@function theme($keys...) {
  $map: $theme;

  @each $key in $keys {
    $map: map-get($map, $key);
  }
  @return $map;
}

// If you don't want to use the custom function 'theme()',
// you can use the native 'map.get($map, $keys...)'
//
// example scss
//
// .element {
//   color: map.get($colors, 'colors', 'gray', '100');
//   background-color: map.get($colors, 'colors', 'gray', '100');
// }
```

After installing the package from `npm`, we use `@use` method to import the `main.scss` file.

More info:

- [Load Paths](https://sass-lang.com/documentation/at-rules/use#load-paths)
- [Choosing a Namespace](https://sass-lang.com/documentation/at-rules/use#choosing-a-namespace)

```scss
// Import package from 'npm' to your app
//
// example scss
//
// @use 'path-to-main-package-file' as *;
//
// or
//

@use 'package-name' as *;
```

Here is an example if the user wants to configure the `$theme` settings:

```scss
// All configuration comes before importing the package

@use 'package-name/theme' with (
  $theme: (
    'breakpoints': (
      'sm': 300px,
      'md': 900px,
      'xxl': 1600px
    ),
    'colors': (
      'lime': rgba(#00ffa2, 1),
    ), 
  )
);

// Main package

@use 'package-name' as *;

// Custom element

.element {
  color: theme('colors', 'gray', '100');
  background-color: theme('colors', 'black');

  @media (min-width: theme('breakpoints', 'md')) {
    color: theme('colors', 'lime');
  }
}
```

That's it. Hope this was helpful. Feel free to close this as resolved.
