### ISSUE TITLE
Format compressed output

### ISSUE THREAD

**Issue by luigifab** [sass/dart-sass#1267]
Is there a way to format compressed output?

**Source SCSS**
```scss
/**
 * Sample comments
 */

/*!
 * Preserve comments
 */

body {
	color: red;
	@media (max-height: 500px) {
		color: blue;
	}
}
```
**Command**
```
# npm install sass
# sass --version = 1.32.8 compiled with dart2js 2.10.5
sass --no-charset --source-map --embed-sources --style compressed abc.scss abc.min.css
```
**Output** (with final empty line)
```css
/*!
 * Preserve comments
 */body{color:red}@media(max-height: 500px){body{color:blue}}/*# sourceMappingURL=abc.min.css.map */
\empty line
```
**Expected output** (without final empty line)
```css
/*!
 * Preserve comments
 */
body{color:red}@media(max-height:500px){body{color:blue}}
/*# sourceMappingURL=abc.min.css.map */
```
