### ISSUE TITLE
@forward behavior based on configuration

### ISSUE THREAD

**Issue by ivodolenc** [sass/dart-sass#1269]
Hi, sorry if this question has already been asked.

I would like to `@forward` files based on a `$theme` configuration so I'm wondering if that's possible.

I tried this example but it doesn't seem to work:

```scss
// utilities/_index.scss

$variable: true;

@if $variable {
  @forward 'font-family'; // doesn't work
}
```

This is my current solution (works as expected) but I’m not sure if this is correct (safe solution).

```scss
// utilities/_index.scss

@forward 'font-family';
```

```scss
// utilities/_font-family.scss

$variable: true;

@if $variable {
  // here goes a file 'content'

  // custom map
  $map: ();

  // custom mixin
  @include mixin {
    //...
  }

  // etc...
}
```

So the file `font-family.scss` will be imported but the `content` will depend on the `$variable` which means if the `$variable` is `false`, an empty `_font-family.scss` file will be imported.

Please, can anyone give some advice on this? Is this ok or does anyone know some better solution?
