### ISSUE TITLE
Bug with @use with null variables

### ISSUE THREAD

**Issue by coenmooij** [sass/dart-sass#1281]
When I overwrite a null value with !default, it works as expected when I render the file, but not when I `@use` it. 

### Working example
```scss
// style.scss

$variable: null;
$variable: 'something' !default;

@debug $variable; // Output: 'something' (expected)
```

### Problem example

```scss
// style.scss

@use 'module' with ($variable: null);

```

```scss
// module.scss

$variable: 'something' !default;

@debug $variable; // Output: null (unexpected)
```

**Comment by danny007in** [comment]
dnot use `$variable: 'something' !default;`
instead use `$variable: 'something';`

**Comment by johannpinson** [comment]
Hello @jathak,

I would like to know more why this behavior has change?
I understand the purpose from @coenmooij, but I thought it more powerful than the older `@import` logic.

Example:

```scss
// module.scss

$defaultColor: blue !default;
$overrideColor: red !default;

a {
  color: $defaultColor;

  + a {
    color: $overrideColor;
  }
}
```

## v1.32.12 - the expected behavior
```scss
// style.scss

@use 'module' with ($overrideColor: null);


// style.css
a {
  color: blue;
}
```

## v.32.13 - the actual behavior
```scss
// style.scss

@use 'module' with ($overrideColor: null);


// style.css
a {
  color: blue;
}

a + a {
  color: red;
}
```

With the possibility to pass `null` into a variable, it makes possible to remove/ignore a property since a rule with a `null` will be omitted during compilation.

I try to find alternative, like using a empty string or `false`, but it prints as `color: ""` or `color: false`
The unique solution may to check each variable if it's *falsey*, which can be hard in a framework logic with hundred of variables.

N.B.: I find a workaround with color/font, like using the "initial/inherit" value, but it doesn't work everywhere (like using `border-color` or `@if` condition)


Thanks for your feedbacks!
