### ISSUE TITLE
 Color name keywords in map

### ISSUE THREAD

**Issue by borisdamevin** [sass/dart-sass#1290]
Hi,

I have an issue with Sass compilation and colors name keywords in map, when we use color name with one of interpoleation style `.bar-#{$color}`, we have a warning in terminal for use another interpolation, the code work but the warning is anoying.

How we can disable this warning without change the interpolation?

### Code

```scss
$colors: (
    white: #ff0000,
    black: #ff0000
);

@each $color in map.keys($colors) {
    .bar-#{$color} {
        color: #{map.get($colors, $color)};
    }
}
```

### Expected Behavior

```css
.bar-white {
    color: #ff0000;
}

.bar-black {
    color: #ff0000;
}
```

### Actual Behavior

```css
.bar-white {
    color: #ff0000;
}

.bar-black {
    color: #ff0000;
}
```

...with terminal warning: 

```shell
You probably don't mean to use the color value white in interpolation here.
It may end up represented as white, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "white").
If you really want to use the color value here, use '"" + $color'.
```
