### ISSUE TITLE
Using multiple "@use ... with()" with different config on same library

### ISSUE THREAD

**Issue by borisdamevin** [sass/dart-sass#1291]
Hi,

Is a way to call twice the same library with `@use ... with()` but with completely different config?

**Example:**

```scss

// component1.scss

@use 'library' with (
    $color: green
);

.foo {
    @include library.foo;
}

```

```scss

// component2.scss

@use 'library' with (
    $color: orange
);

.foo {
    @include library.foo;
}

```

```scss

// index.scss

@use 'component1';
@use 'component2';

```
