### ISSUE TITLE
@use - The target selector was not found.

### ISSUE THREAD

**Issue by larsboldt** [sass/dart-sass#1295]
``` 
colors.scss
%background-white {
  background-color: white;
}

foo.scss
@use "colors";

.foo {
  @extend %background-white;
  padding: 20px;
}

bar.scss
@use "foo";

.bar {
  @extend .foo;
  border: 1px solid black;
}

baz.scss
@use "foo";

.baz {
  @extend .foo;
  border: 1px solid green;
}

total.scss
@use "bar";
@use "baz";

sass total.scss total.css

Error: The target selector was not found.
Use "@extend %background-white !optional" to avoid this error.
  ╷
4 │   @extend %background-white;
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  foo.scss 4:3  root stylesheet
```

Can anyone explain why this is happening?

**Comment by kerryj89** [comment]
Hi @Awjin, while the original issue is fixed, if I have an `@extend` within a `@mixin`, it fails with the same error.

Works now:
```scss
.foo {
  @extend %background-white;
  padding: 20px;
}
```

Doesn't work:
```scss
@mixin test {
  .foo {
    @extend %background-white;
    padding: 20px;
  }
}
```

Do you have any advice here?  I will convert the silent class to be a mixin for now since I don't use the `@extend` much, but it would be nice to know if something in the spec has changed with `@extend` behavior in SASS Module System or if it's a bug.   Thanks!
