### ISSUE TITLE
Extending an extender within a pseudo-selector does not work across modules.

### ISSUE THREAD

**Issue by Awjin** [sass/dart-sass#1297]
When a module extends an upstream `:matches()` pseudo-selector that, in turn, extends a selector from its upstream module, things break.

For example:

```
<===> extendee.scss
.extendee {
  a: 1;
}

<===> extender.scss
@use "extendee";
:matches(.extender) {
  @extend .extendee;
}

<===> extender_of_extender.scss
@use "extender";
.extender_of_extender {
  @extend .extender;
  b: 1;
}
```

This is the expected output:
```scss
.extendee, :matches(.extender, .extender_of_extender) {
  a: 1;
}

.extender_of_extender {
  b: 1;
}
```

This is the current output:
```scss
.extendee, :matches(.extender) {
  a: 1;
}

.extender_of_extender {
  b: 1;
}
```
