### ISSUE TITLE
the behavior of selector.extend does not actually match the extend directive

### ISSUE THREAD

**Issue by stof** [sass/dart-sass#1301]
`@extend` forbids extending a compound selector. However, `selector.extend` happily accepts `a:hover` as its `$extendee` argument.
this makes the doc confusing, as it describes the function as following the same rules than `@extend`: https://sass-lang.com/documentation/modules/selector#extend

Thus, the doc about `@extend` says that `@extend .a:hover` should be replaced with `@extend .a, :hover` as it does the same (and indeed, in libsass, it does the same with a warning). However, passing `.a, :hover` or `.a:hover` to `selector.extend` produces a different behavior than passing `.a, :hover` to `selector.extend`.

```scss
.hoverlink { @extend .a, :hover }
foo .a:hover, bar .a, b :hover { text-decoration: underline }

f { 
    c: selector-extend("foo .a:hover, bar .a, b :hover", ".a, :hover", ".hoverlink") 
}
```

Here is the output with dart-sass 1.32.2:

```css
foo .a:hover, foo .hoverlink, bar .a, bar .hoverlink, b :hover, b .hoverlink {
  text-decoration: underline;
}

f {
  c: foo .a:hover, foo .hoverlink, bar .a, b :hover;
}
```
