### ISSUE TITLE
Undefined variable on @import

### ISSUE THREAD

**Issue by lesar** [sass/dart-sass#1307]
I use npm `sass: ^1.3.12`  and `rollup-plugin-sass: ^1.2.2`  
In my project I like to use bulma css, so I customize my style.scss like this:  
```scss
@charset "utf-8";

// custom variable here
// import from bulma
.colorred { color: red; }

// Fonts
@import url('https://fonts.googleapis.com/css2?family=Roboto&family=Source+Sans+Pro&display=swap');
$family-sans-serif: "Roboto", BlinkMacSystemFont, -apple-system, "Segoe UI", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif !default;
$body-background-color: #181818;
$link-over: $light;

@import "~bulma/sass/utilities/_all";
@import "~bulma/sass/base/_all";
@import "~bulma/sass/elements/_all";
@import "~bulma/sass/form/_all";
@import "~bulma/sass/components/_all";
@import "~bulma/sass/grid/_all";
@import "~bulma/sass/helpers/_all";
@import "~bulma/sass/layout/_all";
```
In `@import "~bulma/sass/utilities/_all";` was defined $light. This is the code:  
```scss
$light: $white-ter !default
```
but when compiling I get:  

> [!] (plugin sass) Error: Undefined variable.
> 22 | $link-over: $light;
> ____________^^^^^^

The import order is what is suggest by bulma.  
The customization above the import is suggest by bulma too.  

I first have think is a bulma bug so have open this [issue:3327](https://github.com/jgthms/bulma/issues/3327)  but now i think that this issue can be related to sass  

can someone help?  
best regards,
Leonardo
