### ISSUE TITLE
Line comments in a multiline calc() statement are printed into the CSS

### ISSUE THREAD

**Issue by Ariane-B** [sass/dart-sass#1311]
Consider the following complex property:

```scss
$numbering-width: 1.2em;
$padding-base: 0.75rem;
$drag-handle-size: 28px;

.something {
  margin:
    $padding-base
    calc(
      #{ $padding-base }
      // + #{ $numbering-width }
      + #{ $drag-handle-size }
    )
    ($padding-base * 2)
  ;
}
```

The commented line will be output as is into the final `calc()` statement, breaking the whole rule. It should probably either recognize the comment and remove it or throw a compilation error saying two consecutive slashes are not valid in this context.
