### ISSUE TITLE
Dart-SASS CLI always compiles a file that uses a built-in module

### ISSUE THREAD

**Issue by Oblomoff** [sass/dart-sass#1335]
### Problem
If the --update flag is specified Dart-SASS always compiles a file that uses a built-in module, ignoring the fact that the file has not been modified.

### Reproduction

Create file test.scss
```SCSS
@use 'sass:map'; // This line causes the problem!

body {
    background-color: white;
}
```
run

```bash
sass --update test.scss test.css
sass --update test.scss test.css
```

### Expected
If the --update flag is passed, Sass will only compile stylesheets whose dependencies have been modified more recently than the corresponding CSS file was generated. 

### Actual

Dart-SASS ignores file was not changed and compiles any time.
