### ISSUE TITLE
@at-root breaks with @use above it

### ISSUE THREAD

**Issue by kerryj89** [sass/dart-sass#1347]
I don't know if this is a bug or some intentional language design gotcha I'm not aware of.

Anyway, I migrated our styles to use `math.div()`.  That worked great, or so I thought...

Apparently `@at-root` breaks when used with `@use` above it:

```scss
//styles.scss

.namespace {
    @import "foobar";
}
```

```scss
//_foobar.scss

@use "sass:math";

@at-root {
    .foo {
        width: math.div(6px, 2);
    }
}

.bar {
    width: math.div(6px, 2);
}
```

If transpiles into the following:

```scss
// styles.css

.namespace .foo {
    width: 3px;
}
.namespace .bar {
    width: 3px;
}
```

I expected the following:

```scss
// styles.css

.foo {
    width: 3px;
}

.namespace .bar {
    width: 3px;
}
```

I tried the following:
- Using `@include meta.load-css("foobar")` instead of `@import`
- Wrapping `@at-root` within a mixin and calling it immediately
- Move `@use` below `@at-root` (errors out as expected, but thought I'd try)

--

If I remove `@use` and just use the division symbol like previously it outputs as expected.

**Comment by jathak** [comment]
@kerryj89: Wanted to give you an update on this. This behavior is definitely a bug, but it's also very difficult to fix, so we've been having trouble getting it to work.

In the meantime, I wanted to offer a workaround that will allow you to use `math.div` without breaking `@at-root`:
```scss
// styles.scss
.namespace {
    @import "foobar";
}

//_foobar.scss
@import "division";

@at-root {
    .foo {
        width: math-div(6px, 2);
    }
}

.bar {
    width: math-div(6px, 2);
}

// _division.scss
@forward "sass:math" as math-* show math-div;
```
