### ISSUE TITLE
Trips up on a comment of only asterisks

### ISSUE THREAD

**Issue by srawlins** [sass/dart-sass#135]
Take the following SCSS, with a weird comment: `/***/`:

```scss
a
/***/
b { margin: 0; }

c {
  /* Comment */
  margin: 0;
}
```

Dart sass doesn't like this:

```none
$ dart bin/sass.dart a.scss
Error: expected "{".
  margin: 0;
           ^
  a.scss 7:12
```

Ruby sass is OK with it, but eats the comment:

```none
$ sass a.scss 
a
b {
  margin: 0; }

c {
  /* Comment */
  margin: 0; }
```
