### ISSUE TITLE
[bug] sass build error, content appears to be none.

### ISSUE THREAD

**Issue by yzqdev** [sass/dart-sass#1388]
```shell
npm install -g sass
# I have already installed the latest version v1.35.1
```

This is my scss file
```scss
// a.scss
@charset "UTF-8";
.icon-lollipop:before {
  content: '\e6a9';
}
```
It's expected to be:
```css
@charset "UTF-8";
.icon-lollipop:before {
  content: '\e6a9';
}
```
But when i run `sass a.scss b.css` , it turns out to be:
```css
// b.css
@charset "UTF-8";
.icon-lollipop:before {
  content: "";
}
```
So, is this a bug, or i did the wrong thing? 
Thanks.
