### ISSUE TITLE
Mixed EOLs in CSS when Error Comments Are Injected

### ISSUE THREAD

**Issue by tajmone** [sass/dart-sass#1392]
Dart Sass 1.35.1

Under Win OS, the generated CSS contains mixed EOLs when there was an error — i.e. the injected error comment introduces some `CRLF` line endings, whereas the generated CSS uses Linux style `LF` EOLs only.

Example from a real case scenario (not committed to a repository):

```css
/* Error: Undefined variable.
 *    ,
 * 25 |   color: $PML-Normal-Text;
 *    |          ^^^^^^^^^^^^^^^^
 *    '
 *   _common.scss 25:10  @import
 *   rouge.scss 10:9     root stylesheet */

body::before {
  font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
      "Droid Sans Mono", monospace, monospace;
  white-space: pre;
  display: block;
  padding: 1em;
  margin-bottom: 1em;
  border-bottom: 2px solid black;
  content: "Error: Undefined variable.\a    \2577 \a 25 \2502    color: $PML-Normal-Text;\d\a    \2502           ^^^^^^^^^^^^^^^^\a    \2575 \a   _common.scss 25:10  @import\a   rouge.scss 10:9     root stylesheet";
}
```

The `CRLF` sequence is found in the line:

```css
 * 25 |   color: $PML-Normal-Text;
```

So, apparently, no all error-injection functions are using inconsistent EOL, only some of them are.
