### ISSUE TITLE
`min` and `max` don't recognize decimals without leading integer

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1394]
Not sure if this is considered a bug, but wanted to clarify behavior here.

For the given input
```scss
a {
  color: min(.2, .4);
  color: min(0.2, 0.4);
}
```

`dart-sass` will output

```css
a {
  color: 0.2;
  color: min(0.2, 0.4);
}
```

The cause for this seems to be that [this switch/case](https://github.com/sass/dart-sass/blob/main/lib/src/parse/stylesheet.dart#L2781) doesn't account for a leading decimal when parsing numbers. If this is intentional, it would be good to add this case to the spec tests.
