### ISSUE TITLE
A nested @media query can cause an outer query to be split unnecessarily

### ISSUE THREAD

**Issue by yukulele** [sass/dart-sass#1402]
If `@media` is nested in another `@media`,  next `@media` are repeated.

Example:

input:
```scss
@media (min-width: 500px) {
    body{
        color: black;
        main{
            color:grey;
            @media (max-width: 1000px) {
                color: green;
            }
        }
        h1{
            color: red;
        }
        h2{
            color: blue;
        }
    }
}
```

output:
```css
@media (min-width: 500px) {
  body {
    color: black;
  }
  body main {
    color: grey;
  }
}
@media (min-width: 500px) and (max-width: 1000px) {
  body main {
    color: green;
  }
}
@media (min-width: 500px) {
  body h1 {
    color: red;
  }
}
@media (min-width: 500px) {
  body h2 {
    color: blue;
  }
}
```

expected:
```css
@media (min-width: 500px) {
  body {
    color: black;
  }
  body main {
    color: grey;
  }
}
@media (min-width: 500px) and (max-width: 1000px) {
  body main {
    color: green;
  }
}
@media (min-width: 500px) {
  body h1 {
    color: red;
  }
  body h2 {
    color: blue;
  }
}
```
