### ISSUE TITLE
Multiline selectors in media queries are indented incorrectly

### ISSUE THREAD

**Issue by Kingju777** [sass/dart-sass#1406]
If you put a Selector with more than one line in a ‘@media’ Query the space that is needed to mark the indentation is not put there.

CSS Result (formatting in front of the `body` element wrong)
```
@media screen {
  html,
body {
    height: 100%;
    width: 100%;
  }
```

Corrected Result (corrected by me)
```
@media screen {
  html,
  body {
    height: 100%;
    width: 100%;
  }
```
Problem in `Javascript API`

Original Ticket:
https://github.com/glenn2223/vscode-live-sass-compiler/issues/106

**Comment by connorskees** [comment]
can reproduce this on most recent version. likely due to indentation only being applied to the first line of a selector. this shouldn't affect the semantics of expanded output. 


A bit smaller Sass input and CSS output comparison
```scss
@media screen {
  a,
  b {
    color: red;
  }
}
```
```css
@media screen {
  a,
b {
    color: red;
  }
}
```
