### ISSUE TITLE
`f` is not able to be escaped as `\66` in `@else if`

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1407]
`dart-sass` seems to raise an error for the following inputs
```scss
@if false {
} @else \69 \66 true {
  a {
    color: red;
  }
}
```
```scss
Error: expected "{".
  ╷
2 │ } @else \69 \66 true {
  │         ^
  ╵
```

and
```scss
@if false {
} @else i\66 true {
  a {
    color: red;
  }
}
```
```scss
Error: expected "{".
  ╷
2 │ } @else i\66 true {
  │         ^
  ╵
```

However, when the second escape, `\66`, is replaced with the literal `f`, it seems to correctly parse this statement,
```scss
@if false {
} @else \69 f true {
  a {
    color: \66;
  }
}
```
```css
a {
  color: f;
}
```
