### ISSUE TITLE
Incorrect compilation when extending a class inside a class with an ::after tag that extends a placeholder.

### ISSUE THREAD

**Issue by scott-parkhill** [sass/dart-sass#1448]
### Issue Summary

Compilation is producing `.test-container .test-class-green .test-class-green::after` instead of `.test-container .test-class-green::after`

### SCSS
    .test-container {
        color: blue;
    
        .test-class {
            font-size: 1rem;
    
            %test-placeholder {
                font-weight: 0.5rem;
            }
    
            &-green {
                @extend .test-class;
                background-color: green;
    
                &::after {
                    @extend %test-placeholder;
                    width: 120px;
                }
            }
        }
    }

### Compiled Output
    .test-container {
      color: blue;
    }
    .test-container .test-class, .test-container .test-class-green {
      font-size: 1rem;
    }
    /* This is the trouble line */
    .test-container .test-class .test-class-green::after, .test-container .test-class-green .test-class-green::after {
      font-weight: 0.5rem;
    }
    .test-container .test-class-green {
      background-color: green;
    }
    .test-container .test-class-green::after {
      width: 120px;
    }

### Expected Compiled Output (trouble line only)
    .test-container .test-class .test-class-green::after, .test-container .test-class-green::after {
      font-weight: 0.5rem;

Edit: didn't indent enough for github code blocks.

Edit2: compilation command: `sass ./test.scss ./test.css --no-source-map`. Compiler version 1.37.5.

**Comment by jathak** [comment]
This output is valid.

Starting with a simplified version of your code:
```scss
.test-container {
    .test-class {
        %test-placeholder {
            font-weight: 0.5rem;
        }
        &-green {
            @extend .test-class;
            &::after {
                @extend %test-placeholder;
            }
        }
    }
}
```

Nesting is resolved before extensions, so the above code is equivalent to:
```scss
.test-container .test-class %test-placeholder { font-weight: 0.5rem; }
.test-container .test-class-green { @extend .test-class; }
.test-container .test-class-green::after { @extend %test-placeholder; }
```

Resolving the extends results in the following selectors that should have `font-weight: 0.5rem`:
```
.test-container .test-class %test-placeholder
.test-container .test-container .test-class-green %test-placeholder
.test-container .test-class .test-container .test-class-green::after
.test-container .test-container .test-class-green .test-container .test-class-green::after
```

The first two lines contain placeholders, so they don't appear in the emitted CSS. In the subsequent lines, we can eliminate the duplicate `.test-container` clauses because they're identical, but `.test-class-green` and `.test-class-green::after` are not, so we end up with:

```
.test-container .test-class .test-class-green::after
.test-container .test-class-green .test-class-green::after
```
