### ISSUE TITLE
Encoding issue about SASS integrate with webpack, sass-loader and mini-css-extract-plugin

### ISSUE THREAD

**Issue by sammyhk** [sass/dart-sass#1458]
Considering about the following SCSS which contains non-ASCII character:
```scss
.text:empty::after {
  content: "\2014";
}
```

Using SASS command line `sass in.scss out.css` would produce the the CSS with `@charset "UTF-8";` properly injected, which is expected.
```css
@charset "UTF-8";
.text:empty::after {
  content: "—";
}

/*# sourceMappingURL=out.css.map */
```

When changed the output style to be "compressed" (i.e. `sass --style=compressed in.scss out.min.css`), which do NOT inject `@charset "UTF-8";`, instead it added UTF-8 `BOM` at the beginning of the file.
```css
.text:empty::after{content:"—"}/*# sourceMappingURL=out.min.css.map */
```

When integrated with webpack (sass-loader and mini-css-extract-plugin), the UTF-8 `BOM` being discarded, resulting the generated CSS missing `BOM`.

May I ask if this is the expected behavior? Any way to signal SASS to inject `@charset "UTF-8";` with output style to be "compressed" instead adding UTF-8 `BOM`?

This is a reproducible sample repository (https://github.com/sammyhk/scss-utf8.git).
Execute `npm run sass` which call sass (`sass --style=compressed ./src/in.scss ./dist/in.scss.bom.min.css`) directly produce the CSS file (`./dist/in.scss.bom.min.css`) with UTF-8 BOM included.
Execute `npm run build` which involve `webpack`, `sass-loader` and `mini-css-extract-plugin` produce the CSS file (`./dist/in.scss.min.css`) without UTF-8 BOM.
