### ISSUE TITLE
Problem since 1.40.0 with bootstrap 5

### ISSUE THREAD

**Issue by kris2kris** [sass/dart-sass#1496]
Hello, 

The following code of bootstrap produce a build error since sass 1.40.0 (https://github.com/twbs/bootstrap/blob/main/scss/mixins/_grid.scss)
```
margin-top: calc(var(--#{$variable-prefix}gutter-y) * -1); // stylelint-disable-line function-disallowed-list
margin-right: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
margin-left: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
```
If I remove the minus sign before 1 or .5 it works. I'm not sure that multiplication should failed because of a minus sign.

**Comment by yudielcurbelo** [comment]
Same here.

**Comment by nex3** [comment]
I can't reproduce this with Dart Sass 1.42.0:

```scss
a {
  $variable-prefix: foo-;
  margin-top: calc(var(--#{$variable-prefix}gutter-y) * -1); // stylelint-disable-line function-disallowed-list
  margin-right: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
  margin-left: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
}
```

This produces:

```css
a {
  margin-top: calc(var(--foo-gutter-y) * -1);
  margin-right: calc(var(--foo-gutter-x) * -0.5);
  margin-left: calc(var(--foo-gutter-x) * -0.5);
}
```

as expected.

What version of Sass are you using? Can you provide a minimal stylesheet that reproduces the issue?
