### ISSUE TITLE
Incorrect interpolation

### ISSUE THREAD

**Issue by radiocity** [sass/dart-sass#1506]
Code :poop:: 
```scss
@mixin delayList {
  $start: 0;
  $end: 10;
  $class: "delay";

  @for $i from $start through $end {
    $iletter: $i * $end/2;
    @if $iletter < $end {
      $iletter: 0#{$iletter};
    }

    $i: $i/2;
    .#{$class}-#{$iletter} {
      animation-delay: #{$i/2}s;
    }
  }
}
@include delayList;
```

Returns: 
```
SassError: expected selector.
    │     .delay-0 0{
    │              ^
```

What is expected (based on node-sass):  
```
 .delay-00 {
  -webkit-animation-delay:0s;
  animation-delay:0s
}
```
