### ISSUE TITLE
First-class calc() does not process CSS variables

### ISSUE THREAD

**Issue by lehni** [sass/dart-sass#1518]
Input:

```scss
$widths: 20, 40, 60, 80, 100;

.item {
  @each $width in $widths {
    &--w#{$width} {
      --width: calc($width * 1%);
    }
  }
}
```

Expected Output:

```css
.item--w20 {
  --width: 20%;
}
.item--w40 {
  --width: 40%;
}
.item--w60 {
  --width: 60%;
}
.item--w80 {
  --width: 80%;
}
.item--w100 {
  --width: 100%;
}
```

Actual Output:

```css
.item--w20 {
  --width: calc($width * 1%);
}
.item--w40 {
  --width: calc($width * 1%);
}
.item--w60 {
  --width: calc($width * 1%);
}
.item--w80 {
  --width: calc($width * 1%);
}
.item--w100 {
  --width: calc($width * 1%);
}
```
