### ISSUE TITLE
Keep CSS variables in compiled code

### ISSUE THREAD

**Issue by netdjw** [sass/dart-sass#1520]
I use SCSS code in my Laravel 8 project with sass. I want to handle switching dark mode and light mode and manually overwrite the browser settings too and I want to use CSS variables to this solution.

Here is my SCSS code:
```scss
// colors in light mode
$color-primary: hsl(19, 8%, 52%);
$color-primary-hover: hsl(17, 8%, 45%);

// colors in dark mode
$color-dark-primary: hsl(18, 27%, 52%);
$color-dark-primary-hover: hsl(17, 8%, 57%);

@media (prefers-color-scheme: light) {
    :root {
        --color-primary: #{$color-primary};
        --color-primary-hover: #{$color-primary-hover};
    }
}

@media (prefers-color-scheme: dark) {
    :root {
        --color-primary: #{$color-dark-primary};
        --color-primary-hover: #{$color-dark-primary-hover};
    }
}

// overwrite light mode
@media (prefers-color-scheme: light) {
    body.forceDarkMode {
        --color-primary: #{$color-dark-primary};
        --color-primary-hover: #{$color-dark-primary-hover};
    }
}

.btn-primary {
    background-color: color(primary);

    &:hover {
        background-color: color(primary-hover);
    }
}
```

I created this function to try to fix this issue:
```scss
@function color($color-name) {
    @return var(--color-#{$color-name});
}
```

And the compiled result is this:

```css
.btn-primary {
  background-color: undefined;
}
@media (prefers-color-scheme: dark){
  .btn-primary{
    background-color: #a67764;
  }
}
@media (prefers-color-scheme: light){
  .btn-primary{
    background-color: #8e817b;
  }
}

.btn-primary:hover {
  background-color: undefined;
}
@media (prefers-color-scheme: dark){
  .btn-primary:hover{
    background-color: #9a8e89;
  }
}
@media (prefers-color-scheme: light){
  .btn-primary:hover{
    background-color: #7c6f6a;
  }
}
```

Of course on the body element I toggle forceDarkMode class name with JavaScript when user change a checkbox.

Now I think the undefined value is shomehow related to my basic problem: I expect something like this code:

```css
.btn-primary {
  background-color: var(--color-primary);
}
@media (prefers-color-scheme: dark){
  .btn-primary{
    background-color: var(--color-primary);
  }
}
@media (prefers-color-scheme: light){
  .btn-primary{
    background-color: var(--color-primary);
  }
}
```

I think the sass compiler change the CSS variables (more precisely the `var(--css-variable-name)` string) to SCSS variable's value.

How can I avoid this replace and keep the CSS variables in the code? Is there any option for this or where should I looking for solutions?
