### ISSUE TITLE
using @extend doesn't work as expected

### ISSUE THREAD

**Issue by MrBrN197** [sass/dart-sass#1528]
I'm reading the sass docs (the how it works section of the `@extend` keyword)
https://sass-lang.com/documentation/at-rules/extend#how-it-works

if I have CSS such as this.

```scss
.content .sidebar {
  @extend .info;
}

.guide .info {
  background-color: red;
  color: greenyellow;
}
```

when I run that through sass I get the output >>
```css
.guide .info, .guide .content .sidebar, .content .guide .sidebar {
  background-color: red;
  color: greenyellow;
}
```

so there three parts to the selector the first is `.guide .info` which is fine
the second and third are `.guide .content .sidebar` and `.content .guide .sidebar`

what I'm wondering is that with the way `@extend` seems to be explained (in the docs) it acts as if `.sidebar` has the class `.info` as well;
so going with this in mind then shouldn't there be a selector that is `.content.guide .sidebar`; that is, we will apply the '.info' properties to the `.sidebar` class if it's parent has both `.guide` and `.content` class names. because in my mind the `.info` properties should be applied to anything that has a parent of `.guide` and also anything that is a `.sidebar` and has a parent of `.content`. Can I get some clarification on this? Is this the intended behaviour of `@extend`?
