### ISSUE TITLE
CSS variable (custom property) with fallback as nothing compiles to no fallback

### ISSUE THREAD

**Issue by yairEO** [sass/dart-sass#1593]
https://www.sassmeister.com/gist/64d412cd7fcc65d2fd09d10c89cb2e0f

```css
div {
    transform: translate(100px) var(--transform-y, );
}
```

The `, ` at the end is valid CSS and is no mistake and should not be removed after compiling.

Read more about it in this article:

https://dev.to/yaireo/optional-css-transform-with-css-variables-e81
