### ISSUE TITLE
Sass not replacing sass variable with value

### ISSUE THREAD

**Issue by navanshu** [sass/dart-sass#1601]
Hey I am `@use` for loading some sass variable and storing it in a css variable but it is not working.
But it is working otherwise.

```scss
@use "./palletteQuad.scss";
@use "./palletteTriad.scss";

// Working
.item1 {
 border: 2px solid palletteQuad.$color-complement-1;
}

// Not working
.item2 {
 --invalid: palletteTriad.$color-secondary-2-1;
}
```
