### ISSUE TITLE
DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables. Consider adding `$theme-map: null` at the root of the stylesheet

### ISSUE THREAD

**Issue by Vinsurs** [sass/dart-sass#1602]
As saied above, i get this deprecation notice in my console when i run my project. so what's this mean? 
But when I adding `$theme-map: null` at the root of the stylesheet i got a running error, what can i do? Any example?

**Comment by stof** [comment]
without sharing your code triggering this, it is hard to help.

> i got a running error

what error did you get ?

**Comment by Vinsurs** [comment]
@stof code as follows:
```scss
// theme.scss
$themes: (
  10: (
    primary-color: #b38344,
    white-color: #fff,
  )
```
```scss
// style.scss
@import "./themes.scss";
@mixin themeify {
  @each $theme-name, $map in $themes {
    .theme-#{$theme-name} {
      $theme-map: () !global;
      @each $key, $value in $map {
          $theme-map: map-merge(
            $theme-map,
            (
              $key: $value
            )
          ) !global;
      }
      @content;
      $theme-map: null !global;
    }
  }
}
@function themed($key) {
  @return map-get($theme-map, $key);
}
```
when i import `style.scss` in my component style file:
```scss
@include themeify {
  .a {
      color: themed("primary-color");  // it works
  }
  .index__share_btn {
    --button-primary-background-color:  #{themed("white-color")};  // it does not works
  }
}
```
so when i use the mixin as above, the css-var `--button-primary-background-color` seems does not works。How can i do with it ?

**Comment by MatteuSan** [comment]
In the `style.scss` file you should add `$theme-map: null;` in the beginning after the `@import`
```scss
$theme-map: null;
@mixin themeify {
  ...
}
```

**Comment by nsvot** [comment]
// default
$default-primary-color: rgba(10, 0, 58, 1);
$default-primary-opp-color: white;
$default-secondary-color: rgba(105, 43, 203, 1);
$default-text-primary-color: white;
$default-text-primary-opp-color: #000000;
$default-text-secondary-color: grey;

$themes: (
  default: (
    backgroundColor: $default-primary-color,
    textColor: $default-text-primary-color,
    buttonTextTransform: none,
    buttonColorPrimary: $default-primary-color,
    buttonTextColorPrimary: $default-primary-opp-color,
    buttonColorSecondary: $default-primary-opp-color,
    buttonTextColorSecondary: $default-text-primary-opp-color,
  ),
  light: (
    backgroundColor: #fff,
    textColor: #408bbd,
    buttonTextColor: #408bbd,
    buttonTextTransform: none,
    buttonTextHoverColor: #61b0e7,
    buttonColor: #fff,
    buttonBorder: 2px solid #fff,
  ),
  dark: (
    backgroundColor: #222,
    textColor: #ddd,
    buttonTextColor: #aaa,
    buttonTextTransform: uppercase,
    buttonTextHoverColor: #ddd,
    buttonColor: #333,
    buttonBorder: 1px solid #aaa,
  ),
);

Above is _variables.scss

Below is _mixins.scss

@import "./_variables.scss";
$theme-map: ();

@mixin themify($themes) {
  @each $theme, $map in $themes {
    .theme-#{$theme} & {
      $theme-map: () !global;
      @each $key, $submap in $map {
        $value: map-get(map-get($themes, $theme), "#{$key}");
        $theme-map: map-merge(
          $theme-map,
          (
            $key: $value,
          )
        ) !global;
      }
      @content;
      $theme-map: null !global;
    }
  }
}

@function themed($key) {
  @return map-get($theme-map, $key);
}


Iam using it in a scss file 
@import "../../../assets/styles/_mixins.scss";

.auth-left {
  flex: 4;
  @include themify($themes) {
    background-color: themed("backgroundColor");
    color: themed("textColor");
  }
}


not working, please provide the solution.
thank you

**Comment by MatteuSan** [comment]
@nsvot it compiles fine for me though 😕

**Comment by nsvot** [comment]
are you using react?

**Comment by MatteuSan** [comment]
> are you using react?

nope, though it works similarly if i use react.

**Comment by nsvot** [comment]
i used another mixin just to check if it is working or not. the flow is fine and the other mixin is working.
I think there is some problem with themify mixin.

i added it in stackoverflow as well. please check
https://stackoverflow.com/questions/76617229/sass-not-working-as-expected-i-have-been-importing-a-mixin-from-a-scss-file-whi

**Comment by MatteuSan** [comment]
> i used another mixin just to check if it is working or not. the flow is fine and the other mixin is working. I think there is some problem with themify mixin.

I don't know what your expected output is supposed to be (since you didn't provide it), though here is what I got from the code you provided in this issue (not the stackoverflow one):

Debug console:

<img width="1621" alt="image" src="https://github.com/sass/dart-sass/assets/39852553/4062ca6a-1c90-4fcb-82ce-6ef4bd2ec06f">


Compiled sass file:
```css
.auth-left {
  flex: 4;
}
.theme-default .auth-left {
  background-color: rgb(10, 0, 58);
  color: white;
}
.theme-light .auth-left {
  background-color: #fff;
  color: #408bbd;
}
.theme-dark .auth-left {
  background-color: #222;
  color: #ddd;
}

/*# sourceMappingURL=main.css.map */
```
