### ISSUE TITLE
First-class calc() does not process CSS three variables

### ISSUE THREAD

**Issue by tgioer** [sass/dart-sass#1606]
Input:
```scss
$hd: 2;
$padding-base: 4px * $hd;
$padding-xs: $padding-base * 2;
$avatar-spacing-small: var(--avatar-spacing-small, var(--avatar-spacing, var(--padding-xs, $padding-xs)))

.avatar {
  margin-left: calc(#{$avatar-spacing-small} * -1);
}
```

Expected Output:
```css
.avatar {
  margin-left: calc(var(--avatar-spacing-small, var(--avatar-spacing, var(--padding-xs, 16px))) * -1);
}
```

Actual Output:
```
Stack:
JisonParserError: Parse error on line 1:
...--avatar-spacing-mini, var(--avatar-spacing, var(--padding-xs, 16px))) * -1
------------------------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
```
