### ISSUE TITLE
import url() is not exported to the top level

### ISSUE THREAD

**Issue by itchyny** [sass/dart-sass#1607]
Importing a sass file including a url() importing at-rule, typically Google fonts, yields the import at-rule inside the selector, unlike node-sass.
```css
/* _us.scss */
@import url("//fonts.googleapis.com/css?family=Roboto:300");
body {
  border: 0;
}

/* index.scss */
[data-region="US"] {
  @import "us";
}
```

Got
```css
[data-region=US] {
  @import url("//fonts.googleapis.com/css?family=Roboto:300");
  body {
    border: 0;
  }
}
```

Expected (node-sass)
```css
@import url("//fonts.googleapis.com/css?family=Roboto:300");
[data-region=US] {
  body {
    border: 0;
  }
}
```
