### ISSUE TITLE
When color is same, @each will skip the loop.

### ISSUE THREAD

**Issue by dodoto** [sass/dart-sass#1624]
vue: 3.0.0
sass: 1.26.5
sass-loader: 8.0.2

$colora: yellow;
$colorb: blue;
$colors: $colora, $colora, $colorb;
@each $color in $colors {
&nbsp;&nbsp;$i: index($colors, $color);
&nbsp;&nbsp;.colors-item:nth-child(#{$i}) {
&nbsp;&nbsp;&nbsp;&nbsp;        background-color: $color;
&nbsp;&nbsp;&nbsp;&nbsp;        &::after {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          content: $i + '';
&nbsp;&nbsp;&nbsp;&nbsp;       }
&nbsp;&nbsp;     }
 }

the result is:
yellow1, not set, blue3.
what I expect:
yellow 1, yellow 2, blue 3.

**Comment by voltaek** [comment]
"yellow 2" is not a possibility with this setup due to how `index()` [works](https://sass-lang.com/documentation/modules/list#index) (emphasis mine):

> `index($list, $value)`
> Returns the [index](https://sass-lang.com/documentation/values/lists#indexes) of $value in $list.
> If $value doesn’t appear in $list, this returns [null](https://sass-lang.com/documentation/values/null). If $value appears multiple times in $list, this returns _**the index of its first appearance**_.

Running your code on [SassMeister](https://www.sassmeister.com/) with Dart Sass v1.26.10 (the oldest version they have) shows exactly that, where it outputs styling for index "1" twice.

```CSS
.colors-item:nth-child(1) {
  background-color: yellow;
}
.colors-item:nth-child(1)::after {
  content: "1";
}

.colors-item:nth-child(1) {
  background-color: yellow;
}
.colors-item:nth-child(1)::after {
  content: "1";
}

.colors-item:nth-child(3) {
  background-color: blue;
}
.colors-item:nth-child(3)::after {
  content: "3";
}
```
Consider writing a mixin that takes an nth child number and a color as its two parameters and just calling that for the three times you need it.
