### ISSUE TITLE
Current v1.45.1 throwing useless warnings

### ISSUE THREAD

**Issue by stratboy** [sass/dart-sass#1636]
Hi, since updating, I'm getting this kind of warning:

```
WARNING: math.div() will only support number arguments in a future release.
Use list.slash() instead for a slash separator.

67 │     background-position: ($hamburger-width - 36px - get-config(small, side_padding)) (math.div($header-height, 2) - 10px);
```

As you can see, math.div is using a variable, which in turn holds a number. So that warning is wrong totally useless, and I should be able to suppress it, at least.

**Comment by stratboy** [comment]
$header-height is taken from a map, through functions. It always worked perfect till now. Anyway, the map:

```scss
$site-config:(
  application:(
    offcanvas-menu-item-height: 58px
  ),
  small:(
    side-spacing: 20px,
    header-height: 70px
  ),
  large:(
    side-spacing: 0,
    sidebar-width: 270px,
    header-height: 125px,
    footer-height: 90px,
    main-tools-height: 80px,
    right-side-padding: 26px,
    left-side-padding: 10px,
    max-width: 1145px // ex main width
  ),
  xlarge:(
    max-width: 1420px
  )
) !default;
```

The mixins:

```scss
$main-config : null !default;

@function get-map-value($map, $keys...){
  @each $key in $keys { $map: map-get($map, $key); }
  @return $map;
}

@function get-config($keys...){
  @if($main-config){
    @return get-map-value($main-config, $keys...);
  }
}
```

Roughly imported like this:

```scss
@forward '../node_modules/lr-css-modules/base-modules' with (
  $main-config: $site-config, // _utilities > get_config
);
```

Then called like this:

`$header-height = get-config(large, header-height);`
