### ISSUE TITLE
Certain number of extends result in very large selector

### ISSUE THREAD

**Issue by fmeyertoens** [sass/dart-sass#1637]
When extending a selector and the extender contains the target (extendee) the resulting CSS selector suddenly gets very complex after 3 similar extends.

No problem until 3 extends:
SCSS
```SCSS
.a {
    display: none;
}

.b .a {
    @extend .a;
}

.c .a {
    @extend .a;
}

.d .a {
    @extend .a;
}
```
CSS
```CSS
.a, .d .a, .c .a, .b .a {
  display: none;
}
```

Very complex selector from 4 extends onwards:
SCSS
```SCSS
.a {
    display: none;
}

.b .a {
    @extend .a;
}

.c .a {
    @extend .a;
}

.d .a {
    @extend .a;
}

.e .a {
    @extend .a;
}
```
CSS
```CSS
/* dart sass 1.49.7 */
.a, .e .a, .b .e .a, .e .b .a, .c .e .a, .e .c .a, .b .c .e .a, .e .b .c .a, .c .b .e .a, .e .c .b .a, .d .e .a, .e .d .a, .b .d .e .a, .e .b .d .a, .d .b .e .a, .e .d .b .a, .c .d .e .a, .e .c .d .a, .d .c .e .a, .e .d .c .a, .b .c .d .e .a, .e .b .c .d .a, .d .b .c .e .a, .e .d .b .c .a, .c .b .d .e .a, .e .c .b .d .a, .d .c .b .e .a, .e .d .c .b .a, .d .a, .d .e .a, .e .d .a, .d .b .e .a, .b .e .d .a, .d .e .b .a, .e .b .d .a, .d .c .e .a, .c .e .d .a, .d .e .c .a, .e .c .d .a, .d .b .c .e .a, .b .c .e .d .a, .d .e .b .c .a, .e .b .c .d .a, .d .c .b .e .a, .c .b .e .d .a, .d .e .c .b .a, .e .c .b .d .a, .d .e .a, .e .d .a, .b .d .e .a, .e .b .d .a, .d .b .e .a, .e .d .b .a, .c .d .e .a, .e .c .d .a, .d .c .e .a, .e .d .c .a, .b .c .d .e .a, .e .b .c .d .a, .d .b .c .e .a, .e .d .b .c .a, .c .b .d .e .a, .e .c .b .d .a, .d .c .b .e .a, .e .d .c .b .a, .c .a, .c .e .a, .e .c .a, .c .b .e .a, .b .e .c .a, .c .e .b .a, .e .b .c .a, .c .e .a, .e .c .a, .b .c .e .a, .e .b .c .a, .c .b .e .a, .e .c .b .a, .c .d .e .a, .d .e .c .a, .c .e .d .a, .e .d .c .a, .c .b .d .e .a, .b .d .e .c .a, .c .e .b .d .a, .e .b .d .c .a, .c .d .b .e .a, .d .b .e .c .a, .c .e .d .b .a, .e .d .b .c .a, .c .d .e .a, .e .c .d .a, .d .c .e .a, .e .d .c .a, .b .c .d .e .a, .e .b .c .d .a, .d .b .c .e .a, .e .d .b .c .a, .c .b .d .e .a, .e .c .b .d .a, .d .c .b .e .a, .e .d .c .b .a, .b .a, .b .e .a, .e .b .a, .b .e .a, .e .b .a, .b .c .e .a, .c .e .b .a, .b .e .c .a, .e .c .b .a, .b .c .e .a, .e .b .c .a, .c .b .e .a, .e .c .b .a, .b .d .e .a, .d .e .b .a, .b .e .d .a, .e .d .b .a, .b .d .e .a, .e .b .d .a, .d .b .e .a, .e .d .b .a, .b .c .d .e .a, .c .d .e .b .a, .b .e .c .d .a, .e .c .d .b .a, .b .d .c .e .a, .d .c .e .b .a, .b .e .d .c .a, .e .d .c .b .a, .b .c .d .e .a, .e .b .c .d .a, .d .b .c .e .a, .e .d .b .c .a, .c .b .d .e .a, .e .c .b .d .a, .d .c .b .e .a, .e .d .c .b .a {
  display: none;
}

/* libsass 3.5.5 */
.a, .b .a, .c .a, .d .a, .e .a {
  display: none;
}
```

I am wondering whether the latter dart result is the expected behavior and the first is just some heuristic that ends at that point or whether this is a bug.

**Comment by stof** [comment]
`The output of dart-sass is actually the expected one. See https://sass-lang.com/documentation/at-rules/extend for the explanation about how `@extend` works.

Extending `.a` in `.e .a` does not mean applying only the rules of you `.a` selector. It also means applying the rules when there is a `.b` ancestor due to the `.b .a` rule. And when you combine all those 5 rules together, it creates lots of combination (as the various extend rules even overlap with each other).

**Comment by fmeyertoens** [comment]
This is what I suspected and I'm fine with it. In our case the many combinations didn't make any sense and we got the desired result by using a placeholder selector:
```scss
%a {
  display: none;
}

.a {
  @extend: %a;
}

.b .a {
  @extend: %a;
}
...
```
Do you have any insight into why it happens at this specific point and not always (with less than 4 extend rules)? I tried digging into the dart source but couldn't find anything.
