### ISSUE TITLE
@extend produces erroneous selector for nested components.

### ISSUE THREAD

**Issue by deadalnix** [sass/dart-sass#1646]
```scss
%base {
  a: b;
  &:hover {
    c: d;
  }
}

.className {
  @extend %base;
}
```

Produces the following selector: `:hover.className` when we'd expected any sub-selector in the source to come AFTER the class name.
