### ISSUE TITLE
Invalid css is accepted by sass

### ISSUE THREAD

**Issue by emattias** [sass/dart-sass#1648]
This code that fails the [W3C validator](https://jigsaw.w3.org/css-validator/#validate_by_input):

```scss
.foo:where:not(.bar) {
    border: 0;
}
```
is accepted by sass.

The intended code was this:

```scss
.foo:where(:not(.bar)) {
    border: 0;
}
```

notice the parentheses around `:not(.bar)`
