### ISSUE TITLE
Unknown property: 'd'

### ISSUE THREAD

**Issue by KunalTanwar** [sass/dart-sass#1667]
```css
.logo {
  &:hover {
    d: path('/*some different path*/');
  }
}
```
**PS** ~ `.logo` is a `svg`.

The above code compiling and working just fine but giving **Unknown Property Warning**
