### ISSUE TITLE
Nesting can produce invalid selectors

### ISSUE THREAD

**Issue by devongovett** [sass/dart-sass#1677]
Hello! I work on [Parcel CSS](https://github.com/parcel-bundler/parcel-css), a CSS minifier and transformer. Our selector parser is somewhat strict, and will print build errors when it encounters something that is invalid in browsers. One of these cases is most kinds of selector components after a pseudo element. Browsers will simply ignore these rules, but as a build tool we error because it is likely that the developer did not intend to write them.

It seems that SASS allows developers to unintentionally generate invalid selectors like this via nesting. For example, this SCSS:

```scss
.foo::after {
  .bar {
    color: red;
  }
}
```

compiles to:

```scss
.foo::after .bar {
  color: red;
}
```

This selector is invalid because pseudo elements cannot have child nodes. This is a simple case, but I think it may be more likely to occur when more advanced features such as mixins are used. Such selectors have shown up in popular libraries such as Blueprint: https://github.com/palantir/blueprint/issues/5256.

I think SASS should probably error when an invalid selector would be generated. This way, developers of libraries using SASS won't unintentionally publish invalid CSS that is later consumed by more strict build tools, or completely ignored in browsers.

Alternatively, in some cases, you might be able to do something smart like re-order the components, but I'm not sure this is a good idea. For example:

```scss
.foo::after {
  &.bar {
    color: red;
  }
}
```

could compile to

```scss
.foo.bar::after {
  color: red;
}
```

notice the `.bar` moved before the `::after`. This would only work if there is no combinator involved however.
