### ISSUE TITLE
Using abstract sass classes does not apply nested styles when used on a pseudo selector

### ISSUE THREAD

**Issue by BlindDespair** [sass/dart-sass#1730]
I am trying to extend an abstract class on :host selector in our Angular application and it works well until my abstract class has some nested selector styles.
Imagine this:
```scss
%test-hover {
  color: green;
  &:hover {
    color: gray;
  }
}

:host {
  @extend %test-hover;
}
```

It generates this:
```css
[_nghost-dxc-c100] {
  color: green;
}
```

But should generate this:
```css
[_nghost-dxc-c100] {
  color: green;
}
[_nghost-dxc-c100]:hover {
  color: gray;
}
```

However it works fine when the nested selector does not have &.
```scss
%test-hover {
  color: green;
  :hover {
    color: gray;
  }
}

:host {
  @extend %test-hover;
}
```

Produces this:
```css
[_nghost-gmj-c100] {
  color: green;
}
[_nghost-gmj-c100]   [_ngcontent-gmj-c100]:hover {
  color: gray;
}
```

I believe it should work for :host with & too.

According to [this comment](https://github.com/angular/angular-cli/issues/23423#issuecomment-1164424416) this is a regression which seems to have been introduced in sass version 1.41.0.

To reproduce please close [this project](https://github.com/BlindDespair/angular-issue-46466-repro) and then run:
```
$ npm install
$ ./node_modules/.bin/sass src/app/app.component.scss 
```
