### ISSUE TITLE
[Vue] :deep() selector doesn't compile when using parent selectors

### ISSUE THREAD

**Issue by sjaustirni** [sass/dart-sass#1754]
# Context
We are using deep selectors in our code-base, specifically the `::v-deep` syntax. Recently we have upgraded to the newest Vue 2.x version, which [deprecated](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md#deep-selectors) the `::v-deep` syntax in favour of `:deep()`. We are therefore moving to the new syntax.

# What works
The old syntax works well, but after upgrade it emits warning:

`[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.`
```scss
::v-deep .wrapper {
    display: flex;

    &__element {
        display: block
    }
}
```
---

Also, plain `.deep()` selector works fine:
```scss
:deep(.wrapper) {
    display: flex;
}
```

# The error
We would, however, like to use the `:deep()` with a nested parent selector:
```scss
:deep(.wrapper) {
    display: flex;

    &__element {
        display: block
    }
}
```
## Expected behaviour
It compiles.

## Actual behaviour

```
ERROR in ./PATH/REDACTED
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid parent selector ":deep(.wrapper)"
   ╷
38 │     &__element {
   │     ^^^^^^^^^
   ╵
```

# Addtional info

* Node: `v16.14.2`
* npm: `8.12.1`
* sass: `1.53.0`
* sass-loader: `13.0.2`
