### ISSUE TITLE
map.set results in error

### ISSUE THREAD

**Issue by bronzehedwick** [sass/dart-sass#1771]
Hello! I am having an issue where calling `map.set()` always results in a syntax error, even though I seem to be following the instructions in the documentation.

My test code:

```scss
@use "sass:map";

$my-colors: ("red": "#f00", "blue": "#0ff");

map.set($my-colors, "black", "#000");

.my-selector {
  color: map.get($my-colors, "red");
  background-color: map.get($my-colors, "black");
}
```

And the error produced is:

```
Error: expected "{".
  ╷
5 │ map.set($my-colors, "black", "#000");
  │                                     ^
  ╵
  test.scss 5:37  root stylesheet
```

Tried with version 1.53 and 1.54 of the dart sass command line tool, as well as the JS API, using node 14 and 18.

Any help would be greatly appreciated.

Thanks!
