### ISSUE TITLE
allow setting a seed value for math.random

### ISSUE THREAD

**Issue by MoritzLoewenstein** [sass/dart-sass#1789]
This feature would be very useful for reproducible builds. When using rsync to deploy the css files, every file containing
math.random will get uploaded again, even though there where no changes in the corresponding scss files.

Edit: I ended up using this function as a drop-in replacement for `math.random`:
```scss
@use "sass:math";

$seed: 369;
@function random($max: null) {
    $seed: ($seed * 9301 + 49297) % 233280 !global;
    // decimal number between 0 and 1
    @if($max == null) {
        @return math.div($seed, 233280);
    }
    // int between 1 and $max (including $max)
    @return math.ceil(math.div($seed, 233280) * $max);
}
```
