### ISSUE TITLE
Compressed mode doesn't compress hsl() in some cases

### ISSUE THREAD

**Issue by svivian** [sass/dart-sass#1823]
Reduced test case:

```scss
$blue: hsl(217, 71%, 53%);
$lightblue: lighten($blue, 8%);
$white: hsl(0, 0%, 100%);

.btn-primary {
	background-color: $blue;
	background-image: linear-gradient($lightblue, $blue);
	border-color: darken($blue, 10%);
	color: $white;
}

.btn-link {
	padding: 0;
	background: transparent;
	border: 0;
	color: $blue;
}
```

Using dart-sass 1.55.0 and this command:

    sass --style=compressed --no-source-map test.scss test.min.css

Here is the output I get:

```css
.btn-primary{background-color:#3273dc;background-image:linear-gradient(#558be2, hsl(217deg, 71%, 53%));border-color:#205bbc;color:#fff}.btn-link{padding:0;background:rgba(0,0,0,0);border:0;color:#3273dc}
```

Variable `$blue` isn't converted to hex when it's inside a `linear-gradient`, although `$lightblue` is converted. And `transparent` is converted to a longer format. The correct version, which works in Sass 1.49.7, is:

```css
.btn-primary{background-color:#3273dc;background-image:linear-gradient(#558be2, #3273dc);border-color:#205bbc;color:#fff}.btn-link{padding:0;background:transparent;border:0;color:#3273dc}
```
