### ISSUE TITLE
Support for container queries

### ISSUE THREAD

**Issue by danielbaars** [sass/dart-sass#1840]
Is support for container queries in the works? 

Two examples:

- `container-type: inline-size;` leads to a `Unknown property: 'container-type'` warning.
- `@container (max-width: 400px) { ... }` leads to a `Unknown at rule @container` warning.

These warnings can be turned off of course but much more hindering is the inability to use variables inside container queries like we can with media queries. This does not work for instance: `@container (min-width: $breakpoint) { ... }` while `@media (min-width: $breakpoint) { ... }` does.

Thanks!

**Comment by jathak** [comment]
Those warnings aren't coming from Sass; check your linter. Sass doesn't have any special support for container queries, but they should work fine.

**Comment by michsko544** [comment]
@danielbaars According to [this](https://github.com/sass/sass/issues/3486) issue, if you want to use a variable inside a container media query you have to use interpolation:
`@container (min-width: #{$breakpoint}) { ... }`

**Comment by thomasfrobieter** [comment]
Doesn't seem to work well here, with SASS 1.63.6:

`
.item-list {
  container-type: inline-size;
  display: flex;
  flex-flow: row wrap;
  gap: 1rem;
  &__item {
    flex: 0 0 auto;
    width: 100%;
    @container (min-inline-size: 45em) {
      width: 50%;
    }
  }
}
// If the @container definition is present above, the following selector is damaged, nor I am able to find the @container in the generated CSS file.
.field {
  display: flex;
  align-items: flex-start;
  gap: $grid-gutter-half;
  > img {
    flex: 0 0 auto;
    width: 70px;
  }
}
`

Any ideas why is that?

**Comment by nex3** [comment]
This is the output I see for Dart Sass 1.63.6:

```css
.item-list {
  container-type: inline-size;
  display: flex;
  flex-flow: row wrap;
  gap: 1rem;
}
.item-list__item {
  flex: 0 0 auto;
  width: 100%;
}
@container (min-inline-size: 45em) {
  .item-list__item {
    width: 50%;
  }
}
```

I'm guessing you have something else in your toolchain that's mangling the CSS.
