### ISSUE TITLE
After migrating from node-sass a custom function stopped working and is output as it is

### ISSUE THREAD

**Issue by szymonnowak-st** [sass/dart-sass#1842]
Hi!

I've got a fairly old app that uses `node-sass`. I'm trying to migrate it to `sass` and got almost everything working (huge thanks for the migration scripts!), except one thing. At the top of every file, I'm loading a helper function that stopped working after the migration - it seems like SASS no longer treats it as a function and simply outputs its name as it is.

We use `sass` together with webpack and in `sass-loader` we set `additionalData` option to prepend this function, as it's used in most files. I had to modify it to prepend `@use 'sass:math';`.

Here's how it looked before my changes:
```js
sassLoader.options.additionalData = "@import 'image-url-helper';";
```

Here's how it looks after my changes:
```js
sassLoader.options.additionalData = "@use 'sass:math';\n@import 'image-url-helper';";
```

Here's how `image-url-helper` looks like:
```scss
@function image-url($image-path) {
  @if (str-index($image-path, '/assets/')) {
    $image-path: str-slice($image-path, 9);
  }

  @return url($image-path);
}
```

Now, after this change, wherever I use `image-url`, it's output as `image-url(...)` rather than `url(...)`, e.g.:
```scss
background-image: image-url(/packs/static/glyphicons.png);
```

 The `image-url-helper.scss`  file is still loaded, as I added some dummy classes into it and I can see them in the generated CSS file.

Any ideas what could be wrong?
