### ISSUE TITLE
Inconsistency with @extend and pseudo selectors between versions

### ISSUE THREAD

**Issue by lachlanmcdonald** [sass/dart-sass#1843]
I've noticed an inconsistency with the way `@extend` treats pseudo-selectors that was introduced sometime after 1.53.0.

In version 1.53.0, the following input:

```scss
%test {
	background: yellow;

	& > :first-child {
		color: red;
	}
}

article {
	> header {
		@extend %test;
		margin: 0;
	}

	> section {
		> header {
			@extend %test;
			margin: 0;
		}
	}
}
```

Results in the expected output below (note the `:first-child` selector appearing twice)

```css
article > section > header,
article > header {
  background: yellow;
}

article > section > header > :first-child,
article > header > :first-child {
  color: red;
}

article > header { margin: 0; }
article > section > header { margin: 0; }
```

Where as in versions after 1.53, the output is as follows:

```css
article > section > header,
article > header {
  background: yellow;
}
article > header > :first-child {
  color: red;
}

article > header { margin: 0; }
article > section > header { margin: 0; }
```

Note that the selector `article > section > header > :first-child` no longer appears in the output.

I've tested this on 1.56.2, 1.55.0, and 1.54.9, on MacOS and each version produces the unexpected output. The earliest minor release I can find which does not demonstrate this issue was 1.53.0.
