### ISSUE TITLE
Incorrect compilation when extending %placeholder which has parent selectors inside

### ISSUE THREAD

**Issue by ah-yu** [sass/dart-sass#1862]
Hi sass team，

I am currently facing a problem in the process of migrating `node-sass` to `sass`. See the minimal reproducible example below.

```scss
// test.scss
%foo {
  &:hover {
    background-color: blue;
  }

  @media (min-width: 500px) {
    &,
    &:hover {
      background-color: red;
    }
  }
}

.bar {
  @extend %foo;
}
```

the compilation of `sass`
```css
.bar:hover {
  background-color: blue;
}
@media (min-width: 500px) {
  /* .bar:hover is missing */
  .bar { 
    background-color: red;
  }
}
```
expected compilation(the output of `node-sass`)
```css
.bar:hover {
  background-color: blue; 
}

@media (min-width: 500px) {
  .bar, .bar:hover {
    background-color: red; 
  } 
}
```

**Comment by connorskees** [comment]
This is reproducible without `@media` or placeholder selectors:

```scss
a, a:hover {
    background-color: red;
}

// for comparison only. not necessary for reproduction
a:hover {
    background-color: blue;
}

b {
    @extend a;
}
```

will output

```scss
// missing b:hover
a, b,
a:hover {
  background-color: red;
}

// contains b:hover
a:hover, b:hover {
  background-color: blue;
}
```

Perhaps this is because `b` is being considered a super selector of `b:hover` and so `b:hover` is considered superfluous and is omitted?

![image](https://user-images.githubusercontent.com/39542938/209914560-626a3602-541b-48e5-9d1f-88ab13f7100e.png)

ruby sass does emit the `b:hover`, which I would argue is the correct behavior.
