### ISSUE TITLE
Extension doesn't trim `a > b` when superselector `a b` is present

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1875]
Reopening https://github.com/sass/sass-spec/pull/1872 seems to have exposed a regression in `dart-sass`'s behavior for trimming complex selectors.

The reproduction is:
```scss
a b {
  @extend %c;
}

a > b {
  @extend %c;
}

%c {
  color: red;
}
```

which on the most recent version of `dart-sass` will produce

```css
a b, a > b {
   color: red;
}
```

The expected output (and what `dart-sass` emitted in a prior version) is
```css
a b {
   color: red;
}
```

This is because the presence of `a b` makes `a > b` redundant.
