### ISSUE TITLE
`@import` in selector doesn't strip `:root`

### ISSUE THREAD

**Issue by augustozanellato** [sass/dart-sass#1883]
Hi!
I'm hitting what's probably an edge case nobody thought of.
I'm using `@import` inside a selector in order to have two themes that can be switched by changing a class on an element.
That works fine, what breaks is CSS variables defined in the imported files because the selector is prepended to the `:root` pseudo-class.

EDIT: in my specific use case I don't have control on the imported files, they're just symlinks to CSS files provided by a NPM package, so I can't convert them to .scss and use Sass variables.

MRE: https://gist.github.com/augustozanellato/280268f0215a05c8ff434255e8b335f9

**Comment by connorskees** [comment]
A silly hack that might help depending on what you want:

```scss
:root * {
    @extend :root;
}
```

If you include this anywhere in your stylesheet, it should change the semantics of your selector to be closer to what you want. E.g.

```scss
// emulating the imports
.light  {
    :root {
        color: red;
    }
}

.dark  {
    :root {
        color: red;
    }
}

:root * {
    @extend :root;
}
```

generates

```scss
.light :root, :root .light * {
  color: red;
}

.dark :root, :root .dark * {
  color: red;
}
```

This has a few downsides in the form of larger selectors and that the semantics aren't _exactly_ perfect -- this only applies to children of `.light` and `.dark`. If the change in semantics doesn't affect you, this should be fine.

I don't think it makes sense for the `:root` to be stripped. There might be an argument for having Sass always put `:root` at the start of the selector, but that behavior might be unintuitive for regular nesting.

If possible, the best solution might be to just pre-process the CSS in your build system or just copy the CSS files and modify them by hand.
