### ISSUE TITLE
sass:map - get multiple keys

### ISSUE THREAD

**Issue by tomahl** [sass/dart-sass#1884]
Hi there,

Is there any way to pick multiple keys from a map?. If not, would you please consider adding a new map-function e.g. `map.pick($map, $keys...)`:

```scss
$font-weights: (
    "regular": 400,
    "medium": 500,
    "bold": 700
);

@debug map.pick($font-weights, "regular", "bold"); // ("regular": 400, "bold": 700)
```
 As you can see, that would be the opposite usecase of the exisiting `map.remove` function.

Thanks

**Comment by tomahl** [comment]
Thank you for all the work you put in and for answering my question @jathak but..

I would really appreciate it if you could show me an example. Preferably without having to remap the desired keys with `map.get` like below (couldn't think of any other solution).

```scss
$my-font-weights: (
    'regular': map.get($font-weights, 'regular'),
    'bold': map.get($font-weights, 'bold')
);
```

Example with "pick":
```scss
$my-font-weights: map.pick($font-weights, 'regular', 'bold');
```

In my opnion "pick" is both easier to write and read, especially when dealing with maps with many lines.

In TypeScript we have both the [Pick](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys) and [Omit](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys) utility types and I can really see them being as useful in Sass as they are in TypeScript. We already have Omit `map.remove` so why not add the opposite? :)

Thank you for reconsidering one last time. :)

**Comment by connorskees** [comment]
@tomahl A pretty simple pure Sass implementation could look like this:

```scss
@use "sass:map";

@function map-pick($map, $keys...) {
    $keys-to-retain: ();
    @each $key in $keys {
        $keys-to-retain: map.set($keys-to-retain, $key, true);
    }

    // we first create a list of keys to remove. `map-remove` clones the map,
    // so by passing all the keys in at once, we can avoid superfluous clones
    $keys-to-remove: ();
    @each $key in map.keys($map) {
        @if not map.get($keys-to-retain, $key) {
            $keys-to-remove: append($keys-to-remove, $key);
        }
    }

    @return map.remove($map, $keys-to-remove...);
}

$map: (a: b, c: d, e: f);

a {
    color: inspect(map-pick($map, a));
}
```

You can play around with this [here](https://connorskees.github.io/grassmeister/?v=QHVzZSAic2FzczptYXAiOwoKQGZ1bmN0aW9uIG1hcC1waWNrKCRtYXAsICRrZXlzLi4uKSB7CiAgICAka2V5cy10by1yZXRhaW46ICgpOwogICAgQGVhY2ggJGtleSBpbiAka2V5cyB7CiAgICAgICAgJGtleXMtdG8tcmV0YWluOiBtYXAuc2V0KCRrZXlzLXRvLXJldGFpbiwgJGtleSwgdHJ1ZSk7CiAgICB9CgogICAgLy8gd2UgZmlyc3QgY3JlYXRlIGEgbGlzdCBvZiBrZXlzIHRvIHJlbW92ZS4gYG1hcC1yZW1vdmVgIGNsb25lcyB0aGUgbWFwLAogICAgLy8gc28gYnkgcGFzc2luZyBhbGwgdGhlIGtleXMgaW4gYXQgb25jZSwgd2UgY2FuIGF2b2lkIHN1cGVyZmx1b3VzIGNsb25lcwogICAgJGtleXMtdG8tcmVtb3ZlOiAoKTsKICAgIEBlYWNoICRrZXkgaW4gbWFwLmtleXMoJG1hcCkgewogICAgICAgIEBpZiBub3QgbWFwLmdldCgka2V5cy10by1yZXRhaW4sICRrZXkpIHsKICAgICAgICAgICAgJGtleXMtdG8tcmVtb3ZlOiBhcHBlbmQoJGtleXMtdG8tcmVtb3ZlLCAka2V5KTsKICAgICAgICB9CiAgICB9CgogICAgQHJldHVybiBtYXAucmVtb3ZlKCRtYXAsICRrZXlzLXRvLXJlbW92ZS4uLik7Cn0KCiRtYXA6IChhOiBiLCBjOiBkLCBlOiBmKTsKCmEgewogICAgY29sb3I6IGluc3BlY3QobWFwLXBpY2soJG1hcCwgYSwgZSkpOwp9Cg==)

**Comment by tomahl** [comment]
Thanks, looks really nice. 👍

However, I still think that a built-in function can be justified for all those users who had not been able to come up with a solution like yours on their own. ...And possibly saved a few lines of code. ;)

**Comment by connorskees** [comment]
Using `map.get` instead of `map.remove` we can come up with an even simpler solution:

```scss
@use "sass:map";

@function map-pick($map, $keys...) {
    $new-map: ();

    @each $key in $keys {
        $new-map: map.set($new-map, $key, map.get($map, $key));
    }

    @return $new-map;
}
```

I tend to agree that such functionality should be implemented by users and not Sass itself. This solution shouldn't be too much of a stretch for most users.
