### ISSUE TITLE
Problems with :global selector

### ISSUE THREAD

**Issue by lgmf** [sass/dart-sass#1897]
Hi folks,

I'm having a problem with sass code that uses the `:global` selector.
The same style when using node-sass works as expected.

The code below it's an example that I have here and as you can see the generated output is different

```scss
// FormControl.scss
.FormControl {
  width: 100%;

  :global(&__input) {
    display: block;
    margin: 0 0 5px;
    padding: 17px;
    border-radius: 4px;
    box-shadow: none;
    height: 48px;
    width: 100%;
    font-size: 14px;
    line-height: 1.5;
    color: #272c35;
    background-image: none;
    border: 2px solid #b9bfcb;
    background-color: #fff;
  }

  &__input {
    color: red;
  }
}
```

```css
/* compiled with node-sass */
.FormControl {
  width: 100%;
}
:global(.FormControl__input) {
  display: block;
  margin: 0 0 5px;
  padding: 17px;
  border-radius: 4px;
  box-shadow: none;
  height: 48px;
  width: 100%;
  font-size: 14px;
  line-height: 1.5;
  color: #272c35;
  background-image: none;
  border: 2px solid #b9bfcb;
  background-color: #fff;
}
.FormControl__input {
  color: red;
}
```
```css
/* compiled with sass */
.FormControl {
  width: 100%;
}

.FormControl :global(&__input) {
  display: block;
  margin: 0 0 5px;
  padding: 17px;
  border-radius: 4px;
  box-shadow: none;
  height: 48px;
  width: 100%;
  font-size: 14px;
  line-height: 1.5;
  color: #272c35;
  background-image: none;
  border: 2px solid #b9bfcb;
  background-color: #fff;
}

.FormControl__input {
  color: red;
}
```

Here's a sample project on stackblitz to ilustrate how I'm testing this https://stackblitz.com/edit/node-ko3gwk?file=FormControl.scss,package.json

Can somebody help me on this?

**Comment by nex3** [comment]
Sass only parses selectors inside other pseduo selectors when the pseduo selectors are specified by CSS. `:global()` is a third-party extension, and so won't be parsed this way. Node Sass is parsing it incorrectly here.

You can work around this by writing `@at-root .FormControl :global(#{&}__input)` instead.

**Comment by lgmf** [comment]
> Sass only parses selectors inside other pseduo selectors when the pseduo selectors are specified by CSS. `:global()` is a third-party extension, and so won't be parsed this way. Node Sass is parsing it incorrectly here.
> 
> You can work around this by writing `@at-root .FormControl :global(#{&}__input)` instead.

Awesome! It worked!

```scss
// FormControl.scss
.FormControl {
  width: 100%;

  :global(#{&}__input) {
    display: block;
    margin: 0 0 5px;
    padding: 17px;
    border-radius: 4px;
    box-shadow: none;
    height: 48px;
    width: 100%;
    font-size: 14px;
    line-height: 1.5;
    color: #272c35;
    background-image: none;
    border: 2px solid #b9bfcb;
    background-color: #fff;
  }

  &__input {
    color: red;
  }
}
```

Thank you
