### ISSUE TITLE
Missing quotation marks when looping through a list or list of lists

### ISSUE THREAD

**Issue by alibiss** [sass/dart-sass#1907]
I tried different compilers in VS Code or from [sassmeister.com](https://www.sassmeister.com/) and only libsass is able to compile the way I want. What am I missing here? I also tried forcing quotation marks on one of the elements of the list and the variable is being used properly when not used in the form `#{$variable}`. The expected result would be to have the quotation marks in the attribute selector but the compiled css file is missing them.

```scss
$letters: AAA "BBB" CCC;
$dictionary: $letters;

@each $page in $dictionary {
    @each $letter in $page {
        .icon[data-letter="#{$letter}"] {
            font-size: $letter;
            height: $letter;
            width: $letter;
        }
    }
}
```
```css
.icon[data-letter=AAA] {
  font-size: AAA;
  height: AAA;
  width: AAA;
}

.icon[data-letter=BBB] {
  font-size: "BBB";
  height: "BBB";
  width: "BBB";
}

.icon[data-letter=CCC] {
  font-size: CCC;
  height: CCC;
  width: CCC;
}
```

**Comment by connorskees** [comment]
Here's a minimization of this:

```scss
$letter: "AAA";

[a="#{$letter}"] {
    color: red;
}
```

@alibiss is the lack of quotes affecting the semantics of your CSS in some way? The meaning of the selector shouldn't differ whether or not there are quotes for this input.
