### ISSUE TITLE
Extending :not(...) into :not(:not(...)) crashes

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#191]
The following style crashes the compiler:

```scss
:not(:not(.baz1)) {
  left: 0;
}
:not(.foo) {
  @extend .baz1;
}
```
