### ISSUE TITLE
Sass compiles VERY slowly since `v1.59` (8 times slower than `v1.58`)

### ISSUE THREAD

**Issue by Elysiome** [sass/dart-sass#1913]
# Introduction

Hi,

I've just migrated from `v1.58.3` to `v1.59.2`, and since, Sass compiles **VERY VERY VERY** slowly. It worked fast under `v1.58.3`. My Node.js is `v18.14.2`.

| Sass version | Node.js version | Compilation time |
| :----------: | :-------------: | :---------: |
|   `1.58.3`   |   `18.14.2`    |     28 seconds      |
|   `1.59.2`   |   `18.14.2`    |     3 minutes and 55 seconds      |

Has anyone encountered a similar issue? Thanks. 👍

# Scenario

I'm using the JavaScript API of Sass through https://github.com/dlmanning/gulp-sass.

# Screenshots

 `v1.58.3`:

![v1 58 3](https://user-images.githubusercontent.com/59090546/224739015-3d307a15-afd1-4dd3-8995-8fb283cf20f7.png)

 `v1.59.2`:

![v1 59 2](https://user-images.githubusercontent.com/59090546/224739040-65b859b6-ca4b-4898-abdb-151b54c3592b.png)

**Comment by flannanl** [comment]
I'm seeing the same issue after moving up to `1.59`. I am running the `sass` command directly and my node version is `18.15.0`.

**Comment by jlenos** [comment]
My Sass is erroring out with 1.59+

```
.../node_modules/sass/sass.dart.js:19
self.exports = _cliPkgExportParam ?? exports;
                                   ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    ...
```

**Comment by s100** [comment]
+1 to this issue. In our case the previous compile time was a few seconds, but now it's 15 minutes plus, long enough for our builds to start timing out. I am attempting to put together a minimal reproduction of the problem - as in, a stylesheet which compiles quickly under 1.58 but slowly under 1.59 - but our CSS is very complicated and pulls in a lot of third-party styles, so it's taking me some time. I am guessing that this was introduced under https://github.com/sass/dart-sass/pull/1903/files but that is only a guess. This *doesn't* seem to be anything to do with repeated SCSS module loading - so far my minimal stylesheet is just one (extremely long) file, with no `@import`s.

Something I have noticed is that we make extensive, repeated use of this pattern:

```css
  .#{$prefix}--data-table--short thead tr,
  .#{$prefix}--data-table--short tbody tr,
  .#{$prefix}--data-table--short tbody tr th {
    height: rem(32px);
  }
```

, we have `$prefix: 'bx'` earlier in the CSS. If I inline that variable, making:

```css
  .bx--data-table--short thead tr,
  .bx--data-table--short tbody tr,
  .bx--data-table--short tbody tr th {
    height: rem(32px);
  }
```

then compile time seems to drop back to normal.
