### ISSUE TITLE
Broken :has with modifier compilation

### ISSUE THREAD

**Issue by fabiospampinato** [sass/dart-sass#1937]
I'm on v1.62.0 (latest), and the following:

```scss
.foo {
  &:has(+ &) {
    display: none;
  }
}
```

Is being compiled to this:

```css
.foo:has(.foo) {
  display: none;
}
```

While instead it should be compiled to this:

```css
.foo:has(+ .foo) {
  display: none;
}
```

Basically the `+` inside the `:has` disappeared.
