### ISSUE TITLE
Global function rgba converted a hex color to keyword

### ISSUE THREAD

**Issue by ntnyq** [sass/dart-sass#1940]
## Input

```scss
.box {
  color: rgba(#f00, 1);
}
```

## Expected output

```css
.box {
  color: rgba(255, 0, 0, 1);
}

/* OR */

.box {
  color: #f00;
}
```

## Actual output

```css
.box {
  color: red;
}
```

It's not a serious bug, just think it's unexpected.
