### ISSUE TITLE
Custom at-rules

### ISSUE THREAD

**Issue by WoLfulus** [sass/dart-sass#1954]
Hi!

I'm working on a "toy" (for now) library that heavily relies on SASS, and I was wondering if it would be possible to have support for custom at-rules at some point.

This is because I have a lot of mixins and the usage becomes to verbose with all the `@include` present everywhere.

For example:

```scss
@use "mylib" as *;

@include button(MyButton) {
  @include define-variable(bg-color, color, black);
  @include define-variable(text-color, color, white);
  @include define-variant(size, small medium large);
  
  background-color: variable(bg-color);
  color: variable(text-color);
  
  @include when(size is small) {
    @apply px-3 py-2;
  }
  @include when(size is medium) {
    @apply px-4 py-3;
  }
  @include when(size is large) {
    @apply px-4 py-3;
  }
}
```

and how I imagine it could be written (probably not syntactically correct btw):

```scss
@use "mylib" as *;

@button MyButton {
  @define-variable(bg-color, color, black);
  @define-variable(text-color, default, white);
  @define-variant(size, small medium large);
  
  background-color: variable(bg-color);
  color: variable(text-color);
  
  @when (size is small) {
    @apply px-3 py-2;
  }
  @when (size is medium) {
    @apply px-4 py-3;
  }
  @when (size is large) {
    @apply px-5 py-4;
  }
}
```

It could be just be a shorter syntax to `@include <mixin>` but explicitly importing it as a rule if there's a concern of clashing with builtin CSS at-rules, idk.

I even started playing with transpiling the modified syntax into SCSS for it to become `@include <original>` again, and it would be really nice to have access to the AST too (both for analysis and compiling from an AST). Not only for playing with something like this, but anything that would work on top of SASS, like linters, formatters, documentation generators, and even LSPs so people could write better IDE support extensions - which IMHO is poor atm, even though SASS is out there for quite a while already.

---

Btw, I also tried finding a community on Discord or somewhere that I could chat about it before raising issues, but I haven't found anything, so, does it exist? I'm not sure exactly where I was supposed to create this issue, just let me know if this is not the right place and I'll move it somewhere else.
