### ISSUE TITLE
36 * 2.083333333333% = 74.%, wrong calculation and compilation

### ISSUE THREAD

**Issue by ibrahimBeladi** [sass/dart-sass#2002]
We use a a 48-col grid, and we built it using sass, and we have this rule
```css
.f-grow-36 {
  flex: 0 0 36 * 2.083333333333% !important;
  max-width: 36 * 2.083333333333% !important;
}
```

It is compiled to css as 
```css
.f-grow-36 {
  flex: 0 0 74.% !important;
  max-width: 74.% !important;
}
```

Mathematically, 36 * 2.083333333333 is 75 not 74
Syntactically, `74.%` is not a valid property value in css, it should be either `74%` or `74.0%`

Using sass@1.62.1 (**on a nuxt project**)

Side notes:
- Adding an additional 3 from the number it works (36 * 2.0833333333333% => 75%) 
  - Adding further more digits does not seems to change anything
- Removing a single 3 digit solves the issue for 36, but breaks col-12 (12 * 2.08333333333% => 24.%)
- Removing 2+ 3 digits makes the compiled css valid, but does not provide the accurate numbers for my use case
