### ISSUE TITLE
Container query mixins not appearing to process variables 

### ISSUE THREAD

**Issue by blackfalcon** [sass/dart-sass#2052]
Containers queries in their base form are supported in Sass. But it appears that if you create a mixin with them, they are not processing the variable into the value. See the following example. 

```sass
$auro-grid-breakpoint-lg: 1024px;

@mixin auro_cq-xs {
  @container (max-width: $auro-grid-breakpoint-lg) {
    @content;
  }
}

@mixin auro_breakpoint--lg {
  @media screen and (min-width: $auro-grid-breakpoint-lg) {
    @content;
  }
}

.multiple {
  ::slotted(*) {
    display: block;

    @include auro_cq-xs {
      display: none;
    }
  }

  @include auro_breakpoint--lg {
    color: orange;
  }
}
```

the output is the following: 

```css
.multiple ::slotted(*) {
  display: block;
}
@container (max-width: $auro-grid-breakpoint-lg) {
  .multiple ::slotted(*) {
    display: none;
  }
}
@media screen and (min-width: 1024px) {
  .multiple {
    color: orange;
  }
}
```

Notice the string for the variable `$auro-grid-breakpoint-lg` is simply passed down. It's only when you use interpolation that the value is used. E.g. 

```sass
@mixin auro_cq-xs {
  @container (max-width: #{$auro-grid-breakpoint-lg}) {
    @content;
  }
}
```

### Expectation 

I shouldn't have to use interpolation here when this is not necessary with standard @media queries.
