### ISSUE TITLE
Custom rem() function no longer being overridden as of v1.65

### ISSUE THREAD

**Issue by amxmln** [sass/dart-sass#2064]
I have a custom `rem()` function defined that turns a pixel value into a rem-Value:

```scss
@use 'sass:math';

@function rem($pixels) {
  @if type-of($pixels) == 'number' and not unitless($pixels) {
    @return math.div(math.div($pixels, $pixels * 0 + 1), 16) * 1rem;
  }

  @return math.div($pixels, 16) * 1rem;
}

$max-content-width: rem(1296);
```

As of `v1.65`, SASS supports the CSS `rem()` function, which returns the remainder of a division. Of course, the two functions clash, but I was under the impression that a user-defined function would always override a native function. However, this does not seem to be the case, as the last line in the above snippet throws:

```bash
Error: 2 arguments required, but only 1 was passed.
   ╷
11 │ $max-content-width: rem(1296);
   │                     ^^^^^^^^^
   ╵
  src/assets/styles/helpers.scss 11:21  @use
```

This is unexpected—am I doing something wrong, or is this a regression?
