### ISSUE TITLE
1.67.0 throws an error when calculating percentages

### ISSUE THREAD

**Issue by benjaminprojas** [sass/dart-sass#2082]
We just updated our dependencies this morning and are now getting the following error:

```
[vite:css] [sass] This operation can't be used in a calculation.
   ╷
23 │     $calculated-width: calc(#{$width}% - var(--aioseo-gutter) * #{$gap-divisor});
   │                                      ^
   ╵
  src/vue/assets/scss/app/mixins.scss 23:35       aioseoFlexRowSpan()
  src/vue/components/common/grid/Column.vue 45:3  root stylesheet
```

Our code looks like the following:

```scss
// Calculate the width of a column, including gutter, based on the number of columns it spans.
@mixin aioseoFlexRowSpan($column-span: 1) {
	$column-count: calc(12 / $column-span);
	$width: calc(100 / $column-count);
	$gap-divisor: calc((100 - $width) / 100);
	$calculated-width: calc(#{$width}% - var(--aioseo-gutter) * #{$gap-divisor});

	max-width: $calculated-width;
	flex-basis: $calculated-width;
}
```

I'd like to know:
1. Is this a bug in the latest update?
2. If not, what is the correct way to approach this calculation that has always worked in the past?

**Comment by nex3** [comment]
Sorry, this is an intentional edge-case breakage. As of 1.67.0, interpolation is no longer parsed by treating the entire surrounding calculation as an opaque string. Calculations now follow the same parsing rules as normal Sass expressions.

Adding units via interpolation is an anti-pattern anyway (see [the Sass documentation on units](https://sass-lang.com/documentation/values/numbers/#units)). The best way to handle this is with proper unit arithmetic:

```scss
// Calculate the width of a column, including gutter, based on the number of columns it spans.
@mixin aioseoFlexRowSpan($column-span: 1) {
	$column-count: calc(12 / $column-span);
	$width: calc(100% / $column-count); // this now has the unit %
	$gap-divisor: calc((100 - $width) / 100%); // this now has no units, because it's dividing by %
	$calculated-width: calc($width - var(--aioseo-gutter) * $gap-divisor);

	max-width: $calculated-width;
	flex-basis: $calculated-width;
}
```

I'll consult with the team and see if we can add temporary deprecated support for this edge case.
