### ISSUE TITLE
A little help with changes in 1.67.0

### ISSUE THREAD

**Issue by mattpilott** [sass/dart-sass#2091]
Ive had this long standing function that I use on all projects which has been affected by the changes in the 1.67.0 release, thing is I can't see what I need to do to make it compile now

```scss
// Function
@function clampy($min, $max) {
   // strip unit for the max value for calculation
   $strip: div($max, $max * 0 + 1);
   // calculate the clamp
   $view: div($strip * 16, 1600) * 100vw; //16 = 1rem; 1600 = vw
   // return non-shorthand clamp code for better browser support
   @return min(max(#{$min}, #{$view}), #{$max});
}

// Usage
html {
  --font-h1: 400 #{clampy(1.75rem, 3.125rem)} / 1.3 var(--family);
}
```

The error I get now is:
```zsh
Error: 1.75rem is not a number.

  17 │    @return min(max(#{$min}, #{$view}), #{$max});
     │                ^^^^^^^^^^^^^^^^^^^^^^
```

Any help would be greatly appreciated, thanks

**Comment by nex3** [comment]
We strongly recommend you use built-in Sass modules with namespaces :slightly_smiling_face:. If you write ([playground link](https://sass-lang.com/playground/#eJxNkNFugyAYhe99ipO0SbVTK+vWJTVLerU32AMwSyeJgAHUNY3vvh90yS4IR3/Ox+EwdhmcwM5x586K+3ZXJ8nhgI9BN14anVxuq0LTcdXf062SOsdW8Z8MjwQAnXbeyh6Dlh43Y+FbAZpj5N0g4p+Gd83Q8UgkyzYazggXllc5pgG3QLFHhSewrF7Zf1YRsTFERIxSTP8JS4Y92CmnVVVZ0FU1TjVR2AnvYFaoOs7oY5xWvhV+sBra6MK1xvqW6+tyDRpzXeJ/Ce8FbdZMjnY39D2dDIDLaqdSUkqfbh6hnzkHiZBwzqKk0UwvmmO3n45/i6T1qosFFsXNaF+07IwXirZ5rEWz8u2VEuc4luw5qGzGAaw8Uq82JRdXsrsH6i8VO4oa))

```scss
@use 'sass:math';

// Function
@function clampy($min, $max) {
   // strip unit for the max value for calculation
   $strip: math.div($max, $max * 0 + 1);
   // calculate the clamp
   $view: math.div($strip * 16, 1600) * 100vw; //16 = 1rem; 1600 = vw
   // return non-shorthand clamp code for better browser support
   @return min(max(#{$min}, #{$view}), #{$max});
}

// Usage
html {
  --font-h1: 400 #{clampy(1.75rem, 3.125rem)} / 1.3 var(--family);
}
```

this will work as intended. You can also clean it up by getting rid of the interpolation entirely ([playground link](https://sass-lang.com/playground/#eJxNkF1qwzAQhN99ioEGYqexYzVtCjGFPPUGPYDqKLXAkox+7IaQu3clO9AHsSut5tthGDsFJ7B23Lmj4r5bN1m22+Ez6NZLo7PTZenQ9lwN13ylpN5ipfhvgVsGgH47b+WAoKXHxVj4ToDmGHkfRHpped+GniciSVZJcERcWJ3lmEfcDMUGNZ7BimZhP6QiYZOJhBilmP4TZg8bsMOWTl0Xsa/rcWqIwg74ALNCNWlGl3Fa+Fb4YDW00aXrjPUd1+d5DVpznu1/C+8FFWsmR9WFYaCfEXBa5BRKTu4f6URzxZJSk91TpF+O/4is86pPuZXlxWhfduyIV3L0dFvyZdX7GxndYl+xl9gVd+zAqj3FaXNScSX7a6T+Afl9hsk=)):

```scss

```
@use 'sass:math';

// Function
@function clampy($min, $max) {
   // strip unit for the max value for calculation
   $strip: math.div($max, $max * 0 + 1);
   // calculate the clamp
   $view: math.div($strip * 16, 1600) * 100vw; //16 = 1rem; 1600 = vw
   // return non-shorthand clamp code for better browser support
   @return min(max($min, $view), $max);
}

// Usage
html {
  --font-h1: 400 #{clampy(1.75rem, 3.125rem)} / 1.3 var(--family);
}
---

Here's what's going on here: in Sass 1.67.0, we changed the behavior of CSS calculation functions so that Sass functions with the same name would take precedence over them. This was necessary to roll out new CSS calculation functions like `pow()` and `rem()` without breaking existing users' code.

We do have an exception for the global `min()` and `max()` functions (as well as the global `round()` and `abs()`)—even though Sass functions are always defined with those names, they'll be parsed as CSS calculations if they're valid CSS calculation syntax. But in your specific case, you've added the `min()` and `max()` functions from `sass:math` to the global namespace, which means they take precedence over any CSS calculation functions.

This is why we strongly recommend using functions with namespaces: CSS adds new function names from time to time, and we need to adjust the language to support them. With namespaces, we _know_ exactly when you're referring to a Sass function versus a plain CSS function. If you don't use them, Sass has to guess, and sometimes it guesses wrong.

Sorry for the trouble!
