### ISSUE TITLE
Q&A: How to prevent color names being transformed to hex values

### ISSUE THREAD

**Issue by LordSimal** [sass/dart-sass#2163]
Hey all,

in the scenario of the `-apple-pay-button-style` CSS attribute, it is necessary that the value is actually `black` and not `#000` as you can see [here](https://developer.apple.com/documentation/apple_pay_on_the_web/displaying_apple_pay_buttons_using_css#3667431)
 
Is this possible with the current 1.70 dart-sass package?

**Comment by ntkme** [comment]
``` scss
.apple-pay-button-black {
    -apple-pay-button-style: unquote("black");
}
```
