### ISSUE TITLE
Dependency URLs with a `file` schema fail to resolve

### ISSUE THREAD

**Issue by jathak** [sass/dart-sass#2164]
```scss
// input.scss
@import "file:/tmp/dependency";

// /tmp/dependency.scss
a { b: c; }
```
and equivalents using absolute `file:` URLs fail to compile starting in Dart Sass 1.67.0.
