### ISSUE TITLE
An alternate way to define inheritance by utilizing nesting

### ISSUE THREAD

**Issue by siMobin** [sass/dart-sass#2189]
I'd like to propose a different way to define **inheritance** by nesting the classes within the super class that would allow multiple classes to inherit a class at once without having to inherit them **separately**.

#### For example:

```scss
.a {
    background-color: red;
    color: white;
    padding: 1em;
}

@extend .a {
    .b {
        margin: 1em;
    }

    .c {
        padding: 5em;
    }

    .d {
        background-color: blue;
    }
}
```
