### ISSUE TITLE
font-awesome integration

### ISSUE THREAD

**Issue by Aetherinox** [sass/dart-sass#2223]
Hey,

Some time ago, I decided to update dependencies.

I have a custom loader which implements font-awesome, which worked great. However, when I updated dart-sass to `1.49.10`. I've pinned it breaking down to that exact version. Everything before still works great.

The core issue is that with 1.49.10, instead of the font-awesome icon class containg the code for the icon, such as:
```
content: "\f00a"
```

the css for each icon displays:

```
.fa-lock:before {
    content: "\gb(2";
}
```

Side note, I have tried to push straight to a newer version, but the issue appears to be the same, which is why I've been working with 1.49.10 so that it's easier to pin-point the issue.

I've peeled through the code in that version of sass, and most of what I can see is there being some additional color functionality added, and I can't seem to find anything in the changelog, unless I'm missing something.

I don't want to throw too much code at you so I'll try to keep it to the relevant points, but this is the just:

`webpack.config.js`:

```js
{
    test: /\.s?css$/,
    use: [
        MiniCssExtractPlugin.loader,
        { loader: 'css-loader', options: { sourceMap: bDev } },
        { loader: 'postcss-loader', options: { sourceMap: bDev } },
        { loader: 'sass-loader', options: { sourceMap: bDev } },
        { loader: 'scss-icons-loader' }
    ]
},
{ test: /fontawesome.*\.woff2$/, loader: 'fontawesome-loader' },
```

<br />

`'scss-icons-loader`

```js
const fs = require('fs');
const path = require('path');

module.exports = function loadScss(scssSource) {
    const cb = this.async();
    const iconScssPath = path.resolve('app/styles/base/_icon-font.scss');

    this.addDependency(iconScssPath);

    fs.readFile(iconScssPath, 'utf-8', (err, iconScss) => {
        if (err) {
            return cb(err);
        }

        scssSource +=
            '\n' +
            [...iconScss.matchAll(/\n\$fa-var-([\w-]+):/g)]
                .map(([, name]) => {
                    return name;
                })
                .map((icon) => {
                    return `.fa-${icon}:before { content: $fa-var-${icon}; }`;
                })
                .join('\n');
        cb(null, scssSource);
    });
};
```

<br />

For the `fontawesome-loader`: https://gist.github.com/Aetherinox/22dc630174352280d5d65ed3768ebf9f

---

<br />

Some type of direction would be great, as I'd love to get up to the latest version. All the other deprecated things were simple, but this one has my head puzzled.

Appreciate it.

**Comment by valenzine** [comment]
I believe this issue has to do with this: https://github.com/sass/dart-sass/issues/568

(I am facing your exact same scenario).

**Comment by Aetherinox** [comment]
Ah, interesting.
I just picked apart the code, and I believe it is coming from

```scss
@function next-fa-glyph() {
    $fa-glyph-counter: $fa-glyph-counter + 1 !global;

    $lo-part: $fa-glyph-counter % 256;
    $hi-part: math.div($fa-glyph-counter - $lo-part, 256);
    $hex-num-str: str-slice(#{rgb($hi-part, $lo-part, 1)}, 2, 5);

    $glyph: unquote('"\\#{$hex-num-str}"');

    @debug "divider offset: #{$glyph}";

    @return $glyph;
}
```

Most specifically, the line `$glyph: unquote('"\\#{$hex-num-str}"');` so I have to see what has changed.
