### ISSUE TITLE
Update to mimic new CSS nesting appears to break use of @include

### ISSUE THREAD

**Issue by Kurohyou** [sass/dart-sass#2292]
Started up a project today using SASS 1.77.8.

Got a host of deprecation warnings that my scss was going to become nonfunctional when scss updates to mimic the css nesting behavior.

However, the sections of code that are triggering this deprecation warning are using `@include` to include code from other mixins. I have typically put all of my includes at the top of a given style declaration like so:

```scss
@mixin baseHeader{
  @include baseText;
  color:var(--fontColor);
  display: block;
  white-space: nowrap;
  margin-top: 0px;
  margin-bottom: 0px;
  font-weight:normal;
}
```
However, according to the deprecation warnings, because the mixin that is included contains other nested scss, this will break when the update occurs.

It seems to me that this change will also break most uses of include. Previously, you could include your mixins anywhere and they would work. Now you will have to consider whether the mixin has any nested scss in it to place it accordingly, however this doesn't guarantee that it will work. Consider what happens if you have several mixins that each have direct style declarations and nested styling:
```scss
@mixin nested-1{
  font-weight: bold;
  > *{
    font-style: italics;
  }
}
@mixin nested-2{
  font-size: 120%;
  > *{
    text-decoration: underline;
  }
}
.final-use{
  border: 1px solid black;
  @include nested-1;
  @include nested-2;
}
```

According to the deprecation warnings, this will no longer work because it parses out to:
```scss
.final-use{
  border: 1px solid black;
  font-weight: bold;
  > *{
    font-style: italics;
  }
  font-size: 120%;
  > *{
    text-decoration: underline;
  }
}
```
This essentially means that if you are using mixins, you now need to wrap everything in the mixin in`&{}` so that you can guarantee it will work in any and all situations in which the mixin might be called.
