### ISSUE TITLE
How to prevent global variable re-defined when imported more than once?

### ISSUE THREAD

**Issue by aztack** [sass/dart-sass#2299]
I'm trying to prevent a global variable from being re-defined (returning to the initial value) by testing its existence with `global-variable-exists` function and initializing it only if it doesn't exist (the first time imported): 

global.scss:
```scss
@use "sass:meta";
@use "sass:map";
@if not global-variable-exists(global) {
	$global: null !global;
}
@if $global == null {
	$global: (default: (user: (name: "a", age: 2)));
} @else {
	@debug("global already initialized");
}
```
a.scss:
```scss
@use "sass:map";
@import './global.scss';

$global: map.deep-merge($global, (default: (user: ("name": 'aa', "age": 33))));
@debug($global);

@import './global.scss';
@debug($global);
```

Here is the output of running sass a.scss:
```bash
Deprecation Warning: As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.

Recommendation: add `$global: null` at the stylesheet root.

  ╷
4 │     $global: null !global;
  │     ^^^^^^^^^^^^^^^^^^^^^
  ╵
    global.scss 4:2  @import
    a.scss 2:9       root stylesheet

a.scss:5 Debug: (default: (user: (name: "aa", age: 33)))
global.scss:9 Debug: global already initialized
a.scss:8 Debug: (default: (user: (name: "aa", age: 33)))
```

But I got the deprecating warning above.
If I add `$global: null` at the stylesheet root. `$global` will be set to null every time `global.scss` is imported and this makes the testing pointless. 

Is there a recommended way to prevent a scss file from being imported multiple times?
