### ISSUE TITLE
Shadowed variables override outer scope

### ISSUE THREAD

**Issue by alecgibson** [sass/dart-sass#2301]
Consider this SCSS:

```scss
div {
  $background: blue;

  span {
    $background: green;
    background: $background;
  }

  background: $background;
}
```

According to [the docs](https://sass-lang.com/documentation/variables/#shadowing):

> Local variables can even be declared with the same name as a global variable. If this happens, there are actually two different variables with the same name: one local and one global. This helps ensure that an author writing a local variable doesn’t accidentally change the value of a global variable they aren’t even aware of.

Given that, I'd expect the compiled CSS:

```css
div {
  background: blue;
}
div span {
  background: green;
}
```

But what I *actually* get is:

```css
div {
  background: green;
}
div span {
  background: green;
}
```

Using v1.77.8

[Playground](https://sass-lang.com/playground/#eJwzNEzJLFOo5lJQUElKTM5OL8ovzUuxUkjKKU215gKKFhck5oGl0RSkF6Wm5lmDxZGFkdSAJGtBRuCUr+UCAI7yJ0k=?s=L1C1-L11C1)

**Comment by alecgibson** [comment]
Or perhaps the docs truly mean "global"?

If I have 

```scss
$background: blue;

div {
  span {
    $background: green;
    background: $background;
  }

  background: $background;
}
```

It works as expected:

```css
div {
  background: blue;
}
div span {
  background: green;
}
```

But I still find the original result highly surprising.
