### ISSUE TITLE
Compressible colors inside a native css functions are not compressed

### ISSUE THREAD

**Issue by ntkme** [sass/dart-sass#2351]
``` scss
body {
  $color-start: rgb(0, 0, 0);
  $color-stop: rgb(255, 255, 255);
  color: $color-start;
  background-color: $color-stop;
  background-image: linear-gradient(180deg, $color-start, $color-stop 90%);
}
```

``` css
body{color:#000;background-color:#fff;background-image:linear-gradient(180deg, rgb(0, 0, 0), rgb(255, 255, 255) 90%)}
```

The color `rgb(0, 0, 0)` is compressed as `#000` when directly used as a property value, however, when the same color is used inside `linear-gradient()`, the color is not compressed.

https://sass-lang.com/playground/#eJwzNEjKT6lUqOZSUFBJzs/JL9ItLkksKrFSKEpP0jDQUQAhTWtk2fwCiKSRqamOAowAKwGrsEIxBySclJicnV6UX5qXoouuIr8ATUFmbmJ6qpVCTmZeamKRbnpRYkpmal6JhqGFQUpqug6K0TrIxihYGqgC3VALAG1YQOY=
