### ISSUE TITLE
--watch not working with 1.79.x

### ISSUE THREAD

**Issue by tmikeschu** [sass/dart-sass#2373]
Hello! When I upgrade to 1.79.4 (I've also tried lower 1.79 versions), watch mode no longer works nor emits an initial build file.

This is my build command:

```
    "build:sass": "sass ./app/assets/stylesheets/v1.sass.scss:./app/assets/builds/v1.css --load-path=node_modules --embed-sources --style=compressed",
```

If I run `build:sass` it creates `v1.css` but if I run `yarn build:sass --watch` nothing happens and I get no errors even with `--verbose`.

<details>
<summary>Here is my v1.sass.scss</summary>

```scss
@import '@blueprintjs/core/lib/css/blueprint';
@import '@blueprintjs/datetime/lib/css/blueprint-datetime';
@import '@blueprintjs/select/lib/css/blueprint-select';
@import '@blueprintjs/datetime2/lib/css/blueprint-datetime2';

trix-toolbar .trix-button-group {
  background-color: transparent;
  border: none;
  margin: 0;
}

trix-toolbar {
  margin-bottom: 8px;
}

trix-toolbar .trix-button--icon {
  width: 2em;
  border-radius: 4px;
}

.trix-button {
  border-bottom-color: transparent !important;

  &[data-trix-attribute='code'] {
    display: none;
  }
}

trix-toolbar .trix-button:not(:first-child) {
  border-left: none;
}

.trix-button:hover {
  background-color: #f0f0f0;
}

.trix-content .attachment--file {
  align-items: center;
  background-color: rgba(19, 124, 189, 0.15);
  border: 0;
  border-radius: 3px;
  color: #4c90f0;
  display: inline-flex;
  flex-direction: row;
  font-size: 12px;
  line-height: 16px;
  margin: 0 2px 2px 0;
  max-width: 100%;
  min-height: 20px;
  min-width: 20px;
  padding: 2px 6px;
  position: relative;
}

.bp5-input {
  box-shadow:
    0 0 0 0 rgb(19 124 189 / 0%),
    0 0 0 0 rgb(19 124 189 / 0%),
    inset 0 0 0 1px rgb(16 22 26 / 15%),
    inset 0 1px 1px rgb(16 22 26 / 20%);
}

.bp5-dark .bp5-input {
  box-shadow:
    0 0 0 0 rgb(19 124 189 / 0%),
    0 0 0 0 rgb(19 124 189 / 0%),
    0 0 0 0 rgb(19 124 189 / 0%),
    inset 0 0 0 1px rgb(16 22 26 / 30%),
    inset 0 1px 1px rgb(16 22 26 / 40%);
}

.bp5-drawer-header {
  position: sticky;
  top: 0;
  z-index: 1000;
  background-color: #fff;
}

/* Remove browser arrow */
select {
  -moz-appearance: none;
  -webkit-appearance: none;
  appearance: none;
  background-image: none;
}

/* For honeypot inputs - removes them from screen */
.hp {
  opacity: 0;
  position: absolute;
  top: 0;
  left: 0;
  height: 0;
  width: 0;
  z-index: -1;
}
```
</details>

Thanks!
