### ISSUE TITLE
Media query "and" keyword is missing the required trailing space when compressed output is used

### ISSUE THREAD

**Issue by alademann** [sass/dart-sass#239]
Hi there!

When implementing the [compressed style option](https://github.com/sass/dart-sass/pull/217) in [sass_builder](https://github.com/dart-league/sass_builder/pull/29), I noticed that the `and` keyword within a media query loses the trailing space that is necessary for it to work in the browser.

### Reduced test case

_Given an `.scss` file like this:_
```scss
body { background-color: black; }
@media screen and (min-width: 768px) {
  body { background-color: rebeccapurple; }
}
```

_The compressed CSS output should be:_
```css
body{background-color:#000}@media screen and (min-width:768px){body{background-color:#663399}}
```

_Instead, the compressed CSS output is:_
```css
body{background-color:#000}@media screen and(min-width:768px){body{background-color:#663399}}
```

_Which causes the background of the body to not switch to `rebeccapurple` when the viewport width is `768px` or wider_

P.S. Thanks for everything you do @nex3 !!!
