### ISSUE TITLE
Quotes not being retained around the value of an attribute selector with a double-dash prefix

### ISSUE THREAD

**Issue by jee-mj** [sass/dart-sass#2392]
## Issue

This is loosely related to #852. 

When a scss file is compiled using `sass@^1.80.1` as well as `sass@^1.79.4` it does not retain quotation marks around attribute selector values that begin with a double dash-- which can be incorrectly parsed as a dashed-ident. This will always return a validation error. 

### Validation Error

Take for instance the following source code pushed through a validator:
```css
.my-element[class$="--text"] {
  color: red;
}
.my-element[class$='--text'] {
  color: red;
}
.my-element[class$=--text] {
  color: red;
}
.my-element[class$="-text"] {
  color: red;
}
.my-element[class$='-text'] {
  color: red;
}
.my-element[class$=-text] {
  color: red;
}
```

Running this through [The W3 CSS Validation Service](https://jigsaw.w3.org/css-validator/) returns a single error, which is the standard behaviour of Dart Sass.

![image](https://github.com/user-attachments/assets/1f5c8e5e-b72f-4fe4-9044-8a961a2fac26)

## Example

package.json
```json
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@eslint/js": "^9.11.1",
    "@types/react": "^18.3.10",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "eslint": "^9.11.1",
    "eslint-plugin-react-hooks": "^5.1.0-rc.0",
    "eslint-plugin-react-refresh": "^0.4.12",
    "globals": "^15.9.0",
    "typescript": "^5.5.3",
    "typescript-eslint": "^8.7.0",
    "vite": "^5.4.8",
    "sass": "^1.80.1"
  }
}
```

### Input
style.scss
```scss
.my-element {
  &[class$="--text"] {
    color: red;
  }
}
```
### Output
index.css
```css
.my-element[class$=--text]{color:red}
```

## Resolution

This issue can be solved either in this transpiler or in the CSS validator as all modern browsers using Gecko, Blink, or WebKit are rendering the style correctly. However, it may render incorrectly based on context though it has to be seen where this actually breaks styles and not parsers.

It should be possible to resolve this error by retaining quotation marks around any text in an attribute selector that is polymorphically both a dashed ident and an ident.

Given that this is an edge case, I believe that it should be resolved in this package and not in the W3 CSS Validation Service-- which is a free hosted service universally used by front-end developers.
