### ISSUE TITLE
Trailing space added for Unicode values for numbers

### ISSUE THREAD

**Issue by RoelN** [sass/dart-sass#2479]
[Example in playground](https://sass-lang.com/playground/#eJwzNFTJz0u1UogxNrTmUikoTQQyUw0MDKy5uFIyy6ysklLT8otSFaq5FBSS8/NKUvNKrBRK8wpL80tSNZRilJSrQdprY5SUNK25aqF6EtNKUovwaQFaA9MCAIx/JtU=)

The following code:

```scss
$one: \31;
$pua: \e000;

div::before {
  content: unquote("\"#{$one}\"");
}

div::after {
  content: unquote("\"#{pua}\"");
}
```

results in the following CSS:

```css
div::before {
  content: "\31 ";
}

div::after {
  content: "\e000";
}
```

Please see the space added after `\31`. This is being added when using the Unicode value for the number `1`, but not for the Unicode value for characters in the PUA. The latter is correct, there shouldn't be a trailing space.
