### ISSUE TITLE
Clarification on interpolation nesting

### ISSUE THREAD

**Issue by vikigenius** [sass/dart-sass#2520]
I am building a parser for sass, and I am confused on how to handle nested interpolation.

I just have this scss file

```scss
$num: 1;

.awe-#{#{$num}} {
  padding-left: 0;
}
```

It seems like SASS is compiling it to

```css
.awe-1 {
  padding-left: 0;
}
```

The documentation does not mention anything about nested interpolation or I don't understand how it's supposed to be parsed. Should it not be an error? Is nested interpolation allowed?
