### ISSUE TITLE
Importing CSS to create nested styles

### ISSUE THREAD

**Issue by kolking** [sass/dart-sass#2551]
SASS allows to include an external CSS file and make it scoped by placing `@include meta.load-css('external-style')` inside style rules. However, if the external stylesheet contains `:root {...}` the result is not what I would expect. Here's the example:

```scss
// external-style.css

:root {
  --button-color: red;
}
.button {
  color: var(--button-color);
}
```

```scss
// stylesheet.scss

.my-app-scope {
  @include meta.load-css('external-style');
}
```

This will produce the following CSS:

```scss
.my-app-scope :root {
  --button-color: red;
}
.my-app-scope .button {
  color: var(--button-color);
}
```

As a result, the `--button-color` variable is undefined because `:root { ... }` has been placed inside `.my-app-scope`. Nesting the `:root` probably makes no sense, so it would be good to exclude the root rules from nesting.
