### ISSUE TITLE
Less-than-ideal formatting of loud comments with weird indentation

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#263]
The following input:

```scss
div {
     /* one
  *     two
  *     three
  */
  top: 10px;
}
```

produces this output:

```css
div {
  /* one
  *     two
  *     three
  */
  top: 10px;
}
```

This isn't ideal, since it doesn't preserve the indentation of the first line relative to the rest of the comment. I'd expect the output to match the input. See also https://github.com/sass/libsass/issues/2566.
