### ISSUE TITLE
Space should be removed around combinators in compressed mode

### ISSUE THREAD

**Issue by nazar-pc** [sass/dart-sass#285]
SCSS:
```scss
a > b {
    color : red;
}
```
ruby-sass's compressed output:
```css
a>b{color:red}
```
dart-sass's compressed output:
```css
a > b{color:red}
```

Definitely a minor issue, but a bit annoying to see compiled files as changed in git when source files are not after switch from ruby-sass.
