### ISSUE TITLE
Duration units are removed from zero values in compressed output

### ISSUE THREAD

**Issue by alademann** [sass/dart-sass#297]
Hi there @nex3,

Using both Dart Sass `1.1.1` and `1.2.0`, the following `.scss` produces invalid CSS output, with the `s` duration unit removed from the `0` value _(which is required per the specification)_:

```scss
// .scss
.foo {
  transition: width .3s ease 0s;
}

.bar {
  transition-duration: 0s;
}
```

Compiles to _(when using compressed output)_:

```css
/* .css (produced via Dart Sass) */
.foo{transition:width .3s ease 0}.bar{transition-duration:0}
```

Note that it occurs in both short-hand and long-hand property values.

The `s` unit remains intact when using the default `expanded` `outputStyle`.

The compressed output produced by both Ruby Sass and LibSass is correct:

```css
/* .css (produced via Ruby / LibSass) */
.foo{transition:width .3s ease 0s}.bar{transition-duration:0s}
```

cc/ @evanweible-wf @maxwellpeterson-wf
