### ISSUE TITLE
Support Microsoft-style binary = operator

### ISSUE THREAD

**Issue by FDiskas** [sass/dart-sass#31]
```
  filter: alpha(opacity=$opacity-ie);
                        ^
```

```scss
@mixin opacity($opacity) {
  opacity: $opacity;
  // IE8 filter
  $opacity-ie: ($opacity * 100);
  filter: alpha(opacity=$opacity-ie);
}
```
