### ISSUE TITLE
wrong sourcemap url?

### ISSUE THREAD

**Issue by maozhenhua2** [sass/dart-sass#364]
win10 64
use Dart_x64.stable.setup.exe install to C:\Dart
dart-sass-1.6.1-windows-x64.zip to C:\Dart\dart-sdk\bin
![image](https://user-images.githubusercontent.com/7087532/41587748-7cd99ace-73e2-11e8-9770-9428d1a8038b.png)

run cmd:

```sh
sass scss:css2
```

```
scss
-test.scss
css2
-test.css
-test.css.map
```

### **test.scss**

```scss
body{color:#fff;}
```

### **test.css**

```css
body {
  color: #fff;
}
/*# sourceMappingURL=css2/test.css.map */ 
```

should be 

```css
/*# sourceMappingURL=test.css.map */
```

### **test.css.map**

```json
{"version":3,"sourceRoot":"","sources":["../scss/test.scss"],"names":[],"mappings":"AAAA;EACE","file":"test.css"}
```
