### ISSUE TITLE
Duplicate values in array generate duplicate index values when printed with a loop

### ISSUE THREAD

**Issue by alanalvarado** [sass/dart-sass#420]
# Consider the next code

```scss
$standard--palette: #f14148, #f14148, #ff4081, #44289a, #44289a, #7c4dff;

@each $color in $standard--palette {
			$i: index($standard--palette, $color);
			.bg-#{$i} {background-color: nth($standard--palette, $i)}
		}
```

## The expected output is

```css
.bg-1 {background-color: #f14148};
.bg-2 {background-color: #f14148};
.bg-3 {background-color: #ff4081};
.bg-4 {background-color: #44289a};
.bg-5 {background-color: #44289a};
.bg-6 {background-color: #7c4dff};
```

## The actual output is

```css
.bg-1 {background-color: #f14148};
.bg-1 {background-color: #f14148};
.bg-3 {background-color: #ff4081};
.bg-4 {background-color: #44289a};
.bg-4 {background-color: #44289a};
.bg-6 {background-color: #7c4dff};
```

As you can see, there isn't 2 or 5 the actual output, but repeated 1 and 4

I am using "grunt": "^1.0.3", "grunt-sass": "^3.0.1", "dart-sass": "^1.10.0",

**Comment by nex3** [comment]
This is intended. `index()` returns the *first* position of the value in the list. If you want to iterate over all the indexes in a list, use `@for`:

```scss
$standard--palette: #f14148, #f14148, #ff4081, #44289a, #44289a, #7c4dff;

@for $i from 1 through length($standard--palette) {
  .bg-#{$i} {background-color: nth($standard--palette, $i)}
}
```
