### ISSUE TITLE
Compilation error with @mixin

### ISSUE THREAD

**Issue by riatorr** [sass/dart-sass#432]
I am using Dart Sass 1.10.0, working on Windows 7 with ASP.NET Core 2.0.

I attempted to create and include my own mixin for `@font-face`. Below are the first 8 lines of my code:

```scss
@mixin font($font-family, $font-path) {
    @font-face {
        font-family: $font-family;
        src: url($font-path);
    }
}

@include font('minionPro', '~/../../fonts/Minion Pro Regular.ttf');
```

However, when trying to compile with the standard `sass input.scss output.css` or `sass --watch input.scss:output.css` this, I get the following error:

```
Error: expected selector.
@mixin font($font-family, $font-path){
^
scss\test.scss 1:1 root stylesheet
```

The compilation fails, and the CSS file I had created for this disappears from the folder. When I remove the `@mixin` and `@include` lines, the code successfully compiles. 

I uninstalled Dart Sass and installed Ruby Sass for a comparision. When I compiled the code with the `@mixin` and `@include` lines, the code successfully compiles.

Here is my full sass code that fails to compile with Dart Sass:

[sass-mixin-example.txt](https://github.com/sass/dart-sass/files/2258527/sass-mixin-example.txt)
