### ISSUE TITLE
Nested variable redefines globally

### ISSUE THREAD

**Issue by AlexWayfer** [sass/dart-sass#444]
Hello!

Output of this code is as expected:

```scss
$my-color: #000;

#logo {
  $my-color: #555;
  color: $my-color;
}

a {
  color: $my-color;
}
```

```css
#logo {
  color: #555;
}

a {
  color: #000;
}
```

But if this code wrapped — local definition of outer variable changes outer variable value:

```scss
body {
  $my-color: #000;
  
  #logo {
    $my-color: #555;
    color: $my-color;
  }
  
  a {
    color: $my-color;
  }
}
```

```css
body #logo {
  color: #555;
}
body a {
  color: #555;
}
```

The same for `libsass`.

Thanks.
