### ISSUE TITLE
Sass crashes when nesting @media queries

### ISSUE THREAD

**Issue by nasso** [sass/dart-sass#453]
I am using Dart Sass 1.12.0 (64-bits) on Windows 10 (64-bits) from the command line.

Here I reduced the problem to the most simplistic example:

```scss
@media (min-width: 640px) {
	@media (min-width: 720px) {
		.stuff {
			color: #123456;
		}
	}

	// REMOVING THIS EMPTY COMMENT WILL CAUSE SASS TO CRASH
	/**/

	.stuff {
		color: #abcdef;
	}
}
```

I compile this from the command line, either directly or using `--watch`.

```
> sass .\example.scss .\example.css
```

It compiles fine.

Though, as stated by the single-line SCSS comment, removing the empty multi-line CSS comment following will cause Sass to crash:

```scss
@media (min-width: 640px) {
	@media (min-width: 720px) {
		.stuff {
			color: #123456;
		}
	}

	// REMOVING THIS EMPTY COMMENT WILL CAUSE SASS TO CRASH
	// (removed)

	.stuff {
		color: #abcdef;
	}
}
```

Compiling this gives:
```
> sass .\example.scss .\example.css
Unexpected exception:
Bad state: No element
```
