### ISSUE TITLE
Can't use @if after @include with content within another @include

### ISSUE THREAD

**Issue by CupOfTea696** [sass/dart-sass#482]
This is a very specific bug, I'm just gonna give some code examples.

The following

```scss
$truthy: true;

@mixin component($name) {
    .#{$name} {
        @content;
    }
}

@mixin part($name) {
    &.#{$name} {
        @content;
    }
}

@include component(c) {
    padding: 20px;
    
    @include part(p) {
        padding: 40px;
    }
    
    @if $truthy {
        border: 1px solid;
    }
}

```

throws this error:

```
Fatal error: expected "{".
  src/test.scss 23:26  root stylesheet
```

Other cases that do work:

```scss
@include component(c) {
    padding: 20px;
    
    @if $truthy {
        border: 1px solid;
    }
    
    @include part(p) {
        padding: 40px;
    }
}
```

```scss
.c {
    padding: 20px;
    
    @include part(p) {
        padding: 40px;
    }
    
    @if $truthy {
        border: 1px solid;
    }
}
```

```scss
@include component(c) {
    padding: 20px;
    
    &.p {
        padding: 40px;
    }
    
    @if $truthy {
        border: 1px solid;
    }
}
```

```scss
@include component(c) {
    padding: 20px;
    
    @include part(p);
    
    @if $truthy {
        border: 1px solid;
    }
}
```
