### ISSUE TITLE
Escaped CSS characters get decoded but not reencoded

### ISSUE THREAD

**Issue by JamyDev** [sass/dart-sass#485]
I've recently bumped into an issue where some code from a layout library [skel](https://github.com/ajlkn/skel) is not correctly compiling in dart-sass where it would correctly compile in ruby-sass.

Input:
```sass
.\31 2u {
  background-color: #FF0000;
}
.test {
  content: '\00DF';
}
```

Expected output (ruby-sass):
```css
.\31 2u {
  background-color: #FF0000;
}
.test {
  content: '\00DF';
}
```

Actual output (dart-sass):
```css
.\12u {
  background-color: #FF0000;
}
.test {
  content: "ß";
}
```

Looks like dart-sass is decoding the unicode characters, but not reencoding them. This is not such a big issue for strings as those will probably work just fine, but it is a bigger issue when used in selectors as it changes the behavior of the stylesheet.
