### ISSUE TITLE
Newline \a does not seem to work in DartSass (works in LibSass) 

### ISSUE THREAD

**Issue by jakob-e** [sass/dart-sass#522]
Example:
````SCSS
$str: "\a foo \a bar\a";
/*#{$str}*/ 

Output:
/* foo  bar */

Expected:  
/*
foo 
bar
*/
`````
Ref: https://github.com/sass/sass/commit/e8b1fb7ef975232d73c0d3137968024b881261b5

**Comment by nex3** [comment]
Upon investigation, this is a bug in LibSass. Ruby Sass also doesn't have the behavior you expect.

Any time a quoted string is converted to an unquoted string, either through interpolation or the `unquote()` function, its newlines are converted into spaces. This ensures that newlines don't mess up the formatting of property values. This also happens in comments, because the logic for converting quoted string to unquoted strings is the same everywhere.

**Comment by jakob-e** [comment]
Then I’m not sure the comments in the referenced commit (last part)

* Unescaped newlines in SassScript strings in SCSS are deprecated, since they're  invalid according to the CSS string grammar. 

To include a newline in a string,
  use "\a" or "\a " as in CSS.

**Comment by nex3** [comment]
`\a` is indeed the escape code to include a newline in a string. What I'm saying is that, when a quoted string goes through interpolation and is converted to an unquoted string, all newlines in it are converted to spaces.

**Comment by jakob-e** [comment]
Could there be an exception in case of multi line comments produced by scss - like in the case of assessment (e.g. true by Miriam Suzanne)?... without it becomes almost unreadable

**Comment by lunelson** [comment]
FWIW I do also use this feature (or bug) a lot, in libsass, in multiline comments--and I believe it actually only works there, not in regular output--I have a function called `map-inspect()` which uses the `\a` character to print maps in expanded form like this:

```scss
$map-nested: (
  alpha: (
    beta: (
      gamma: 3,
      delta: 4,
    ),
    epsilon: 5,
  ),
);

/*
$map-nested: #{map-inspect($map-nested)}
*/
```
```css
/*
$map-nested: (
  alpha: (
    beta: (
      gamma: 3,
      delta: 4
    ),
    epsilon: 5
  )
)
*/
```
...it would be great if dart-sass would allow this, in the multiline-comment context only
