### ISSUE TITLE
css class ordering difference issue

### ISSUE THREAD

**Issue by hawckins** [sass/dart-sass#524]
You can test this https://www.sassmeister.com/ by switching between DartSass and LibSass

Input
-----------

```scss
$oj-fwk-icon-arrow-e: "e601" !default;
$textDirection: null !default;
@function oj-prepend-slash($char)
{
  @return #{"\"\\"}#{$char + "\""};
}
@if  $oj-fwk-icon-arrow-e and $oj-fwk-icon-arrow-e != '' {
      .oj-fwk-icon-arrow-e:before {
        content: oj-prepend-slash($oj-fwk-icon-arrow-e);
      }
      .oj-fwk-icon-arrow-w:before {
        @extend .oj-fwk-icon-arrow-e;
      }
      .oj-fwk-icon-arrow-n:before {
        @extend .oj-fwk-icon-arrow-e;
      }
      .oj-fwk-icon-arrow-s:before {
        @extend .oj-fwk-icon-arrow-e;
      }
      .oj-fwk-icon-arrow-start:before {
          @extend .oj-fwk-icon-arrow-w;
      }
      .oj-fwk-icon-arrow-end:before {
          @extend .oj-fwk-icon-arrow-e;
      }
    }
```

LibSass Output
----------------------

```css
.oj-fwk-icon-arrow-e:before, 
.oj-fwk-icon-arrow-w:before, 
.oj-fwk-icon-arrow-start:before, 
.oj-fwk-icon-arrow-n:before, 
.oj-fwk-icon-arrow-s:before, 
.oj-fwk-icon-arrow-end:before {
  content: "\e601";
}
```

Look at the difference in order

DartSass Output
----------------------

```css
.oj-fwk-icon-arrow-e:before, 
.oj-fwk-icon-arrow-end:before, 
.oj-fwk-icon-arrow-s:before, 
.oj-fwk-icon-arrow-n:before, 
.oj-fwk-icon-arrow-w:before, 
.oj-fwk-icon-arrow-start:before {
  content: "\e601";
}
```

However this is not an issue with validation or execution, but we are transitioning from LibSass to DartSass so we are in a position to compare our stable LibSass css against DartSass created css and we see whole lot of diff in these @extend spots. And it is really hard to resolve all diff's.

Is there any way I can fix this, any help is appreciated.
