### ISSUE TITLE
IE browser hack breaks

### ISSUE THREAD

**Issue by hirofumii** [sass/dart-sass#536]
I found that the dart-sass broke css hack for ie.

## Reproduce error
```sass
body {
  color: #000 \9; // for IE hack
}

@import "import";
```

## Error
```css
body {
  color: #000 \	;  /* broken */
}

body {
  color: #000 \	; /* @import is also the same */
}
```

This is hack for ie10 or earlier, I think that it is rare to use this, but it is used in some famous libraries and it may be affected. (Especially in case of minifying css.)

I would be happy if you could consider dealing with this problem.
Thanks.
