### ISSUE TITLE
Wrong merge of nested negative media queries (with the keyword NOT)

### ISSUE THREAD

**Issue by Revisor** [sass/dart-sass#537]
Hello, I found a few past issues about this, but it still seems unresolved.

Past issue in Ruby Sass : https://github.com/sass/sass/issues/1831 "Nested media queries using the "not" keyword should not be merged"
Past issue in Libsass: https://github.com/sass/libsass/issues/2425 "Negation is ignored when nested media queries exist"
Past issue here, in Dart-Sass: https://github.com/sass/dart-sass/issues/244 "Nested negated media query behavior is wrong"

**Source:**
```scss
@media screen and (hover: hover) {
    @media not all and (any-pointer: coarse) {
        @media not all and (any-pointer: none) {
            .all-conditions {
                display: inline;
            }
        }
    }
}
```

**Expected outcome:**
```css
@media screen and (hover: hover) {
    @media not all and (any-pointer: coarse) {
        @media not all and (any-pointer: none) {
            .all-conditions {
                display: inline;
            }
        }
    }
}
```

**Expected outcome in Media Queries Level 4 syntax**
```css
@media screen and (hover: hover) and (not(any-pointer: coarse)) and (not(any-pointer: none)) {
    .all-conditions {
        display: inline;
    }
}
```
But this syntax is only theoretical and doesn't work yet in Chrome 70 nor FF 63.

**Received outcome in DartSass 1.6.2:**
```
```
(Empty result)

**Received outcome in LibSass 3.5.2:**
```css
@media screen and (hover: hover) and (any-pointer: coarse) and (any-pointer: none) {
  .all-conditions {
    display: inline;
  }
}
```
Wrong rule, the negations have disappeared.

Thank you for taking a look at this.
