### ISSUE TITLE
Can't pass arguments to `@content`

### ISSUE THREAD

**Issue by Herriau** [sass/dart-sass#583]
Steps to reproduce:

1. `$ yarn add sass`
2. `$ ./node_modules/.bin/sass --version`
  `1.16.1 compiled with dart2js 2.1.0`
3. Create `test.scss` with example from spec (sass/sass#871, see below)
4. `$ ./node_modules/.bin/sass test.scss`

```
Error: Only 0 arguments allowed, but 2 were passed.
    @content ($i, 360deg * $i / 5);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  test.scss 3:5  @content
  test.scss 3:5  accepts-content()
  test.scss 7:1  root stylesheet
```

**test.scss**

```sass
@mixin accepts-content {
  @for $i from 1 to 5 {
    @content ($i, 360deg * $i / 5);
  }
}

@include accepts-content {
  @receive ($number, $hue);
  .color-#{$number} {
    background-color: hsl($hue, 75%, 90%);
  }
}
```

**Comment by nex3** [comment]
That's not the syntax for writing an `@include` that takes arguments. You need to write:

```scss
@mixin accepts-content {
  @for $i from 1 to 5 {
    @content ($i, 360deg * $i / 5);
  }
}

@include accepts-content using ($number, $hue) {
  .color-#{$number} {
    background-color: hsl($hue, 75%, 90%);
  }
}
```
