### ISSUE TITLE
Extending a class with applicable :not-selector from within a selector with two classes produces invalid css

### ISSUE THREAD

**Issue by hkrutzer** [sass/dart-sass#588]
Source:

```sass
.foo:not(.baz) {
  text-decoration: none;
}

.quu.quiz {
  @extend .baz;
}
```

This produces
```css
.foo:not(.baz):not(.quu.quiz) {
  text-decoration: none;
}
```
Which is invalid CSS.

Tested in DartSass v1.7.0 and v1.6.2.

(I try to not use extends at all but this bit us in an older project that still uses them).
