### ISSUE TITLE
Nested placeholders create incorrect selectors

### ISSUE THREAD

**Issue by mikeebowen** [sass/dart-sass#625]
When using nested placeholders there are extra selectors created that do not match the rules defined in the code. For example
```sass
.foo %extension {
  color: red;
}

.bar {
  .baz {
    @extend %extension;
  }
}
```

Outputs 
```css
.foo .bar .baz, .bar .foo .baz {
  color: red;
}
```

When the expected output is
```css
.foo .bar .baz {
  color: red;
}
```

We're using the npm package of to compile our sass: https://www.npmjs.com/package/sass

I was also able to recreate the issue on Sasssmeister: https://www.sassmeister.com/gist/95b1647798e996185791d89fefcd77c4

**Comment by mikeebowen** [comment]
I found another case with similar unexpected output that doesn't involve placeholders.
With this Scss:
```scss
@mixin hello-world {
  .hello {
        .world & {
            color: purple;
        }
    }
}

.world-wrapper {
  @include hello-world;
}
```
I would expect:
```css
.world-wrapper .world .hello {
  color: purple;
}
```
but the output is 
```css
.world .world-wrapper .hello {
  color: purple;
}
```
https://www.sassmeister.com/gist/90eb0e3abe09ebe3601dd6d2924ee9c2
