### ISSUE TITLE
String interpolation works differently than in lib sass

### ISSUE THREAD

**Issue by joneff** [sass/dart-sass#718]
The following yields different output in libsass and dartsass:

```scss
$em: 1.2em;
$px: 2px;
$calc: #{$em} + #{$px};

body {
  calc: calc( #{$calc} );
}
```

## Expected result (libsass)

```css
body {
  calc: calc( 1.2em + 2px);
}
```

## Actual result (dartsass)

```css
body {
  calc: calc( 1.2em2px );
}
```
