### ISSUE TITLE
get-function with underscore in function name fails with "Function not found"

### ISSUE THREAD

**Issue by znck** [sass/dart-sass#792]
Demo: https://repl.it/repls/TanHeavyNonlinearprogramming

> I tried to write test but dart is beyond me.

**Comment by lunelson** [comment]
I just hit this too. Took me a while to track it down, seems to have come up in a recent patch.

Sass' internal re-mapping of `_` to `-` on function and variable-names was known to me, but I'd never seen it pose a problem WRT function lookup before. The following code works in libsass and worked in dart-sass as of `1.22.0`, but now fails without any clues as to the reason (`Error: Function not found: test_fn`).

Note that if I assign `$test-fn: get-function('test-fn');`, replacing the `_` with `-` myself, it works.

```scss
@function test_fn($args...) { @return $args; }

$test-fn: get-function('test_fn');

.test {
  output: call($test-fn, foo, bar);
}
```
```css
/* libsass only */
.test {
  output: foo, bar;
}
```
