### ISSUE TITLE
Error: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by dagda1** [sass/dart-sass#801]
I have a sass file that imports a file from `node_modules` using the tilde prefix:

```scss
@import '~@cutting/component-library/src/styles/_index.scss';
```

When I try and run this using `renderSync` I get the following error:

> 3 │ @import '~@cutting/component-library/src/styles/_index.scss';
>   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   ╵
>   Users/paulcowan/projects/cuttingedge/packages/website/src/assets/scss/_main.scss 3:9  @import
>   stdin 1:9                                                                             root stylesheet
>     at Object._newRenderError (/Users/paulcowan/projects/cuttingedge/node_modules/sass/sass.dart.js:10687:19)
>     at Object._wrapException (/Users/paulcowan/projects/cuttingedge/node_modules/sass/sass.dart.js:10537:16)
>     at StaticClosure._renderSync (/Users/paulcowan/projects/cuttingedge/node_modules/sass/sass.dart.js:10512:18)
>     at Object.Primitives_applyFunction (/Users/paulcowan/projects/cuttingedge/node_modules/sass/sass.dart.js:1055:30)
>     at Object.Function_apply (/Users/paulcowan/projects/cuttingedge/node_modules/sass/sass.dart.js:4882:16)

This works when I use the sass-loader and webpack to parse the files [like this](https://github.com/webpack/loader-utils/blob/master/lib/urlToRequest.js#L24).

I am trying to fix a bug in [typescript-plugin-css-modules](https://github.com/mrmckeb/typescript-plugin-css-modules) which uses sass-dart and I would be interested to know if sass-dart supports tilde imports?

I have a failing test which you can reproduce like this:

```bash
git clone https://github.com/dagda1/typescript-plugin-css-modules.git
cd typescript-plugin-css-modules
npm install
git checkout pc/tilde-import
npm test
```

The test file is [here](https://github.com/dagda1/typescript-plugin-css-modules/blob/pc/tilde-import/src/helpers/__tests__/cssSnapshots.test.ts#L12) and the fixture it uses [here](https://github.com/dagda1/typescript-plugin-css-modules/blob/pc/tilde-import/src/helpers/__tests__/fixtures/import.module.scss)

**Comment by dagda1** [comment]
actually, the `~` was a workaround in the sass-loader that was fixed in [this PR](https://github.com/webpack-contrib/sass-loader/pull/447/files).

If I remove this tilde from my import and include `node_modules` in the `includePaths` in renderSync then all is good.

```javascript
      transformedCss = sass
        .renderSync({
          data: css,
          includePaths: [
            filePath,
            'node_modules'
          ],
        })
        .css.toString();
```

**Comment by danny007in** [comment]
but how in dart-sass by [https://www.npmjs.com/package/node-sass-package-importer](url)

**Comment by zaydek** [comment]
@danny007in Try using `--load-path` or `-I`:

```
-I, --load-path=<PATH>         A path to use when resolving imports.
```

**Comment by sattes-faction** [comment]
@zaydek unfortunately that doesn't work, because the '~' is not stripped.

**Comment by danny007in** [comment]
> 
> 
> @zaydek unfortunately that doesn't work, because the '~' is not stripped.

u need to remove `~`

**Comment by sattes-faction** [comment]
Yes I know, but it would be nice if dart sass could follow the webpack scheme here, because the `~` is also recognized across all IDEs properly. In my case I have the issue that a scss file using that import scheme is used by a webpack config and also by the cli dart sass (part of ongoing migration).

In node sass it was possible to use a custom importer  using the `--importer` flag on command line, but that's not possible with dart sass (which is recommended by node sass).

**Comment by danny007in** [comment]
@sattes-faction create new issue for that

**Comment by rodoabad** [comment]
Did you get it to work? I don't think `--include-path` works with scoped packages.

```sass
@use 'sass:math';
@use '@org/branding/styles/variables';
```

Results in...

```css
/* Error: Can't find stylesheet to import.
 *   ,
 * 2 | @use '@org/branding/styles/variables';
 *   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 *   '
 *   src/tooltip/tooltip.module.scss 2:1  root stylesheet */

body::before {
  font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
      "Droid Sans Mono", monospace, monospace;
  white-space: pre;
  display: block;
  padding: 1em;
  margin-bottom: 1em;
  border-bottom: 2px solid black;
  content: "Error: Can't find stylesheet to import.\a   \2577 \a 2 \2502  @use '@org/branding/styles/variables';\a   \2502  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\a   \2575 \a   src/tooltip/tooltip.module.scss 2:1  root stylesheet";
}
```
