### ISSUE TITLE
Can't import angular_components sass files to WebStorm v2019.2

### ISSUE THREAD

**Issue by hamedsbt** [sass/dart-sass#804]
I'm using WebStorm v2019.2 and my config is:
```
environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular:
  angular_components:
  skawa_material_components: ^1.2.0

dev_dependencies:
  angular_test: ^2.3.0
  sass_builder: ^2.1.3
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
```
![01](https://user-images.githubusercontent.com/7298328/63326431-7f725280-c341-11e9-9942-664cf8eae72a.jpg)

![02](https://user-images.githubusercontent.com/7298328/63326435-7f725280-c341-11e9-88c0-415571f280c2.jpg)

![03](https://user-images.githubusercontent.com/7298328/63326975-8d74a300-c342-11e9-8db6-e78494a88a2a.jpg)
