### ISSUE TITLE
Extraspace just before the value of variable

### ISSUE THREAD

**Issue by gaspoute** [sass/dart-sass#808]
Hello,

An extraspace is added just before the variable containing a size unit.

### Steps to reproduce
Execute `echo '$unit: rem; body { padding: 0.8$unit; }' | npx sass --stdin `

### Result
```css
body {
  padding: 0.8 rem;
}
```

### Expected
```css
body {
  padding: 0.8rem;
}
```
Thanks :smiley:
