### ISSUE TITLE
Edge case bug

### ISSUE THREAD

**Issue by gabrielmaldi** [sass/dart-sass#81]
Source:

```sass
%placeholder1 {
    display: none;
}

.class1 {
    @extend %placeholder1;
}

.class2:not(.class3):after {
    display: none;
}
```

dart-sass output:

```css
.class1 {
  display: none;
}

.class2:not(.class3):not(.class3) {
  display: none;
}
```

node-sass output:

```css
.class1 {
  display: none;
}

.class2:not(.class3):after {
  display: none;
}
```
