### ISSUE TITLE
$variable couldn't pass to calc (a built-in function)

### ISSUE THREAD

**Issue by dtvn** [sass/dart-sass#825]
```SCSS
blockquote {
	$borderWid: 3pt;
	padding: 0.5em calc(2em - $borderWid);
	border-left: {
		color: inherit;
		width: $borderWid;
		style: solid;
	}
}
```

Expected result:

```CSS
blockquote {
	padding: 0.5em calc(2em - 3pt);
	border-left-color: inherit;
	border-left-width: 3pt;
	border-left-style: solid;
}
```

Sadness reality:

```CSS
blockquote {
	padding: 0.5em calc(2em - $borderWid);
	border-left-color: inherit;
	border-left-width: 3pt;
	border-left-style: solid;
}
```
Maybe there is something wrong with the parser?
