### ISSUE TITLE
Bad State: The Extender and CssStylesheet passed to cloneCssStylesheet() must come from the same compilation

### ISSUE THREAD

**Issue by Ant59** [sass/dart-sass#843]
Using dart-sass in an Angular environment.

I can't find a root cause to this error. I am importing sheets from the fontawesome library and this error is appearing.

```scss
@use 'responsive';
@use 'colours';
@use 'typography';

@use 'node_modules/@fortawesome/fontawesome-free/scss/fontawesome';
@use 'node_modules/@fortawesome/fontawesome-free/scss/solid';

ul.breadcrumbs {
  width: 100%;
  display: inline-flex;
  border-bottom: 1px solid colours.$colour-divider;
  background-color: colours.$colour-bg;
  padding: 0 20px;
  margin-bottom: 48px;
  position: static;
  @include responsive.not-desktop {
    display: none;
    margin-bottom: 30px;
  }

  li {
    margin-bottom: 0;
    transform: unset;
    padding-right: unset;
    // chevron
    &:before {
      @extend .fa;
      @extend .fa-chevron-right, :before;
      font-size: 10px;
      margin: 0 10px;
      position: static;
      left: unset;
    }
    // no chevron for first link
    &:first-child:before {
      content: none;
      display: none;
    }

    a, span {
      display: inline-block;
      line-height: 40px;
      font-size: 14px;
      font-weight: typography.$font-weight-light;
      text-decoration: none;
      color: colours.$colour-nav-item;
      padding: 0 2px;
    }
    a:hover {
      color: colours.$colour-admiralty-blue;
    }
    span {
      user-select: none;
    }

    &:last-child a {
      color: colours.$colour-admiralty-blue;
      font-weight: typography.$font-weight-medium;
    }

  }

}
```

**Comment by Ant59** [comment]
Further inspection reveals that I'm still getting the same error, even with only one import and no rules.

**Comment by nex3** [comment]
This is still a bug that we'd like to fix, even if you're not running into it yourself! Can you provide a Git repo that reproduces the issue?

**Comment by iammattq** [comment]
I'm also experiencing this bug in a repo I can't share unfortunately. I'll see about re-producing in my personal account here if I can. I'm using the new syntax within a design system library and have fairly interlinked set of variables, mixins and functions. 

The error seems to be coming from a completely unrelated bit of code. I'm use `@use ... with ...` as well as `@use` within various mixins, functions, and variables files and when I comment out a the use of a specific and completely unrelated mixin, this error goes away. I've added debug statements through the mixin and they all run as they should.

Is there a way that I can get a more verbose output from the sass compiler? I'm running it in Angular, but have broken it out into a gulp build using `gulp-dart-sass` and `v1.23` of sass. The error happens in both Angular (ng build) and with gulp.

**Comment by nex3** [comment]
If you can find a way to invoke the compiler CLI directly on your code, you can run the Dart version with `--trace` and get a full stack trace of the issue.

**Comment by iammattq** [comment]
Doesn't seem to tell me much more information. Would the output be helpful to you?

**Comment by iammattq** [comment]
I figured out my problem. I'll try and be as descriptive as I can.

I did a `@use base` in my scss root that @forwards vars and runs an `boot` mixin. Then immediately did a `@use components` and within each component css (loaded via `meta.load_css`) I also did a `@use base` which ran the `boot` mixin again. Every component I was dynamically loading with `meta.load_css` ran the `@use base`. I split the `@use base` into two files, one with just `@forwards` the vars and the other with the `boot` mixin. The components just now `@use base` and my app does both `@use base; @use boot;`. All is well.

**Comment by nex3** [comment]
@iammattq Can you provide an example repository that reproduces the bug?

**Comment by Ant59** [comment]
For me, this error seems to appear when I `@import` a stylesheet which in turn uses `@use`

**Comment by nbrombal** [comment]
I converted a current project of mine to the new `@use`/`@forward` syntax last week and have been seeing this error when replacing some nested `@import` statements with `@include meta.load-css()`. A standard `@import` works perfectly well, but `load-css()` has been choking on something.

After many hours of trying to distill a simple reproduction, the best I can tell is that my issues revolve around media queries nested within selectors. I get errors in the following scenarios:

1. Meta-loading a stylesheet containing a nested media query that `use`s or `forward`s a stylesheet with any form of output (including block comments, and even if the `use`d/`forward`ed stylesheet is a partial).
1. Meta-loading a stylesheet that `use`s or `forward`s a stylesheet containing a nested media query (at any depth in the `use`/`forward` chain).

Reproduction of issue 1:

```scss
// test-a.scss

@use 'sass:meta';

.foo {
    margin: 0;

    @include meta.load-css('test-b');
}
```
```scss
// test-b.scss

@use 'test-c';
// and/or
@forward 'test-c';

.bar {
    margin: 0;

    @media screen {
        margin: 10px;
    }
}
```
```scss
// test-c.scss

/* Any output at all, even a block comment. */
```

Reproduction of issue 2:

```scss
// test-a.scss

@use 'sass:meta';

.foo {
    margin: 0;

    @include meta.load-css('test-b');
}
```
```scss
// test-b.scss

@use 'test-c';
// and/or
@forward 'test-c';
```
```scss
// test-c.scss

.bar {
    margin: 0;

    @media screen {
        margin: 10px;
    }
}
```

It's possible this is intended behaviour and I simply don't fully understand the compilation process. Using the `@import` directive doesn't produce any of these issues, but obviously I'd like to fully replace it. Should I be looking to something other than `load-css()`?
