### ISSUE TITLE
global-variable-exists() doesn't work in modules.

### ISSUE THREAD

**Issue by arpadkdweb** [sass/dart-sass#848]
I ran into an issue where I want to have a default value for a mixin, and I cannot make it work.

```scss
/// module.scss
@mixin hello($width: null) {
  padding: if($width, $width, if(global-variable-exists(hello-width), $hello-width, null));
  @debug global-variable-exists(hello-width); /// false
}

/// main.scss
$hello-width: 2em;
@use "module";
div {
  @include module.hello();
  @debug global-variable-exists(hello-width); /// true
}

/// output.css
div {}
```

**Comment by nex3** [comment]
This is intentional. Variables aren't global in the module system; each module only has access to the variables that it declares or explicitly loads from other modules with `@use`.

If you want to allow modules to have customizable default values, you can either set values after the fact in the downstream modules:

```scss
/// module.scss
$hello-width: null;

@mixin hello($width: null) {
  padding: $width or $hello-width;
}
```

```scss
/// main.scss
@use "module";

module.$hello-width: 2em;

div {
  @include module.hello();
}
```

or you can make it a [configurable variable](https://sass-lang.com/documentation/at-rules/use#configuring-modules) and set it when you load the module:

```scss
/// module.scss
$hello-width: null !default;

@mixin hello($width: null) {
  padding: $width or $hello-width;
}
```

```scss
/// main.scss
@use "module" with ($hello-width: 2em);

div {
  @include module.hello();
}
```
