### ISSUE TITLE
Quotes being removed around the value of an attribute selector without a dot character present

### ISSUE THREAD

**Issue by adamjcook** [sass/dart-sass#852]
## Problem Description

This may or may not be related to #598 - which saw a similar variant of the issue described below.

The basic problem seems to be that the quotes enclosing the value of an attribute selector are removed from the CSS output, **if** a dot (.) is not also included in the value of the attribute selector in some way (either hard-coded before the string interpolation, or part of the resulting interpolated value).

## Details

`index.scss`:

```scss
$prefix: 'box';
$dot-prefix: '.box';
$dash-prefix: '-box';
$prefix-dot: 'box.';

div[class*='#{$dot-prefix}'] {
    padding-left: 0;
    padding-right: 0;
}

div[class*='#{$prefix-dot}'] {
    padding-left: 0;
}

div[class*='.#{$prefix}'] {
    padding-right: 0;
}

div[class*='#{$prefix}'] {
    padding-left: 0;
}

div[class*='#{$dash-prefix}'] {
    padding-left: 0;
    padding-right: 0;
}
```

Once compiled with `sass index.scss:output.css`, the `output.css` file will contain:

```css
div[class*=".box"] {
  padding-left: 0;
  padding-right: 0;
}

div[class*="box."] {
  padding-left: 0;
}

div[class*=".box"] {
  padding-right: 0;
}

div[class*=box] {
  padding-left: 0;
}

div[class*=-box] {
  padding-left: 0;
  padding-right: 0;
}
```

The last two (2) generated rules are incorrect.

## Environment

Windows 10
Node.js v12.9.0
Dart Sass 1.23.0
