### ISSUE TITLE
Global meta.mixin-exists() and hooks

### ISSUE THREAD

**Issue by grig0ry** [sass/dart-sass#867]
The new modular system is great! But how to implement hooks now?

Example:
``` scss
// library.scss (npm package)

@use 'sass:meta';

@mixin grid() {
  display: grid;
  @if (meta.mixin-exists('hook-grid')) {
    @include hook-grid();
  }
}

.grid {
  @include grid();
}
```

``` scss
// project.scss

@use 'node_modules/@scope/package/library.scss';

@mixin hook-grid() {
  grid-template-columns: repeat(4, 1fr)
}
```
