### ISSUE TITLE
@forward-ed files not updated with CLI --watch

### ISSUE THREAD

**Issue by jacobScripts** [sass/dart-sass#870]
OS Windows 10
Node v12.13.0
npm 6.12.0
sass v1.23.2 compiled with dart2js 2.5.2

`sass main.scss:main.css --watch`

```scss
/* files/_variables.scss */
$font-size: 16px;

/* files/_index.scss */
@forward "variables";

/* main.scss */
@use "files" as *;
* {
  font-size: $font-size;
}
```

When using the above `sass --watch` command, there is no recompiling when changes are made to the _variables.scss file. For example, if the following changes were made ...

```scss
/* files/_variables.scss */
$font-size: 16px;
$color: black;

/* main.scss */
@use "files" as *;
* {
  font-size: $font-size;
  color: $color;
}
```

The following error occurs.

```
Error: Undefined variable.
  ╷
3 │   color: $color;
  │          ^^^^^^
  ╵
  main.scss 3:10  root stylesheet
```
