### ISSUE TITLE
Extend fails to work on subselectors in the same selector list

### ISSUE THREAD

**Issue by Zerthox** [sass/dart-sass#873]
I recently switched from node-sass to dart-sass in order to try out the new modules system, but noticed a difference regarding `@extend`.

This is my example SCSS code:
```scss
.foo,
.foo.bar {
  color: red;
}
.foo2 {
  @extend .foo;
}
```
I would expect it to result in:
```css
.foo,
.foo2,
.foo.bar,
.foo2.bar {
  color: red;
}
```
Which is what I get with libsass v3.5.4 and the old ruby-sass implementation.

But with dart-sass v1.23.1 it results in:
```css
.foo,
.foo2,
.foo.bar {
  color: red;
}
```
Extending `.bar` also doesn't work in this scenario.
