### ISSUE TITLE
`@import`-ing two modules with conflicting members should not error

### ISSUE THREAD

**Issue by jathak** [sass/dart-sass#888]
Currently, if two modules that expose members with the same name are loaded via `@import` (or even one module that's imported twice) and one of these members is referenced, Sass errors saying that the member is available from multiple global modules.

e.g.
```scss
// entrypoint.scss
@import "a";
@import "b";

a { color: $var }

// _a.scss
@forward "shared";

// _b.scss
@forward "shared";

// _shared.scss
$var: blue;
```

By the [semantics for `@import`](https://github.com/sass/sass/blob/master/accepted/module-system.md#importing-files) in the module system proposal, members from later `@import` rules should override previous definitions, even if they came from another `@import`.
