### ISSUE TITLE
Can't return @media query from function: isn't a valid CSS value

### ISSUE THREAD

**Issue by johncrim** [sass/dart-sass#898]
The following works in node-sass. I came across this bug when migrating to dart-sass.

Given the following SCSS file (media-test.scss):
``` scss
$min-widths: (
  Small: 600px,
  Medium: 960px,
  Large: 1280px,
  XLarge: 1920px,
);

@function min-width-for($width-name) {
  $width: map-get($min-widths, $width-name);
  @return (min-width: $width);
}

@mixin media-min-width($min-breakpoint-name) {
  @media #{min-width-for($min-breakpoint-name)} {
    @content;
  }
}

//======= Test case #1:
@include media-min-width(Small) {
  p {
    margin-left: 2rem;
    margin-right: 2rem;
  }
}

//======= Test case #2:
@media #{min-width-for('Large')} {
  p {
    margin-left: 4rem;
    margin-right: 4rem;
  }
}

// Works (workaround is to not return map from function - can only return values)
@media (min-width: map-get($min-widths, XLarge)) {
  p {
    margin-left: 6rem;
    margin-right: 6rem;
  }
}
```

Running with node-sass works, but using sass returns the same error for both variations (surely the same bug, but I thought I'd provide alternatives that I'd tried that work with node-sass):

``` bash
$> node-sass media-test.scss
@media (min-width: 600px) {
  p {
    margin-left: 2rem;
    margin-right: 2rem; } }

@media (min-width: 1280px) {
  p {
    margin-left: 4rem;
    margin-right: 4rem; } }

@media (min-width: 1920px) {
  p {
    margin-left: 6rem;
    margin-right: 6rem; } }

$> sass media-test.scss     
Error: (min-width: 600px) isn't a valid CSS value.
   ╷
14 │   @media #{min-width-for($min-breakpoint-name)} {
   │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  media-test.scss 14:12  media-min-width()
  media-test.scss 20:1   root stylesheet
```

This appears to be a bug since it results in valid CSS, and is a breaking change from node-sass without a good workaround.

Requiring the name of the media query name-value-pair to be literally entered after `@media` means that a lot of media expressions can't be generated by sass. Please let me know if a better workaround exists.

**Comment by Awjin** [comment]
The following should work:

```
@function min-width-for($width-name) {
  $width: map-get($min-widths, $width-name);
  @return 'min-width: #{$width}';
}

@mixin media-min-width($min-breakpoint-name) {
  @media (min-width-for($min-breakpoint-name)) {
    @content;
  }
}

//======= Test case #1:
@include media-min-width('Small') {
  p {
    margin-left: 2rem;
    margin-right: 2rem;
  }
}

//======= Test case #2:
@media (min-width-for('Large')) {
  p {
    margin-left: 4rem;
    margin-right: 4rem;
  }
}
```

**Comment by johncrim** [comment]
Thank you @Awjin ! Yes, that works. I should have tried that approach (in fact I started with something similar for my older node-sass version of the code, but removed the interpolation b/c it was causing issues with dart-sass).

Importantly, one can include parentheses in the string, which means that one can build media more complex media queries in functions/mixins:

```scss
<snip>

@function min-width-for($width-name) {
  $width: map-get($min-widths, $width-name);
  @return '(min-width: #{$width})';
}

@mixin media-min-width($min-breakpoint-name) {
  @media #{min-width-for($min-breakpoint-name)} {
    @content;
  }
}

//======= Test case #1:
@include media-min-width(Small) {
  p {
    margin-left: 2rem;
    margin-right: 2rem;
  }
}

//======= Test case #2:
@media #{min-width-for('Large')} {
  p {
    margin-left: 4rem;
    margin-right: 4rem;
  }
}
```

results in:

```css
$> sass media-test.scss     

@media (min-width: 600px) {
  p {
    margin-left: 2rem;
    margin-right: 2rem;
  }
}
@media (min-width: 1280px) {
  p {
    margin-left: 4rem;
    margin-right: 4rem;
  }
}
```

Still, I'd argue that this is a bug (with a much better workaround now), since including a map in a media query works in node-sass, and the error message is misleading.
