### ISSUE TITLE
Incorrect behavior when a stylesheet in a load path is loaded by both `@use` and `@import`

### ISSUE THREAD

**Issue by jathak** [sass/dart-sass#899]
For example:
```scss
// app.scss
@use "library";
@import "library";

// load-path/_library.scss
a { b: regular; }

// load-path/_library.import.scss
a { b: import-only; }
```
should output the regular styles followed by the import-only styles (and it does so if the rules' URLs are relative), but instead it outputs the regular styles twice.

I believe this is due to `ImportCache` using the same canonicalization cache for both `@import` and `@use` rules (I actually ran into this with the migrator initially).
