### ISSUE TITLE
@forward `with` one base file multiple times then @use them together

### ISSUE THREAD

**Issue by whitetrefoil** [sass/dart-sass#913]
Using `sass@1.24.0`.

I'm working on a theming work, but whatever I tried, I got `SassError: This module was already loaded, so it can't be configured using "with".`

I got these files:

```scss
// themes/_default.scss
$color: white !default;
$height: 100px !default;
```

```scss
// themes/_red.scss
@forward "default" with (
  $color: red,
);
```

```scss
// themes/_blue.scss
@forward "default" with (
  $color: blue,
);
```

Then I tried:
```scss
// themes/index.scss
@forward "blue" as blue-*;
@forward "red" as red-*;
@forward "default" as default-*;
// Failed!
```

Tried:
```scss
// app.scss
@use "themes/red" as red-theme;
@use "themes/blue" as blue-theme;
@use "themes/default" as default-theme;

.content {
  color: default-theme.$color;
}

body.theme-red {
  color: red-theme.$color;
}
// Failed!
```
