### ISSUE TITLE
Configuring maps with modules: `@use ... with()`

### ISSUE THREAD

**Issue by vricop** [sass/dart-sass#925]
I've tried configuring a `_config.scss` file that contains variables, lists and mostly maps.

Is it possible to configure map modules or this feature is not part of sass?
If it's not part of sass, do you have plans to implement it?
 
I wonder if I can or could do this:

1. I have a `_config.scss` file where I've got all my default settings. Mostly composed by maps.

```scss
// _config.scss

$colors: (
  // BLACK & WHITE
  'black': #000,
  'white': #fff,
  
  // GRAYSCALE
  'gray-100': #F7F7F7,
  'gray-200': #F2F2F2,
  'gray-300': #D9D9D9,
  'gray-400': #ABABAB,
  'gray-500': #767676,
  'gray-600': #616161,
  'gray-700': #525252,
  'gray-800': #3D3D3D,
  'gray-900': #212121,
  //...
);
```

2. Now I "import" (`@use`) my `_config.scss` into `index.scss` and  I want to **add** a color to my default `$colors` map.

**Note**: With `@use … with()` you can only overwrite variables.

```scss
// index.scss

/* 1. Notice I'm trying to add a new color to the default set, not overwrite it */
@use 'sass:map';

@use 'config' with (  
  $colors: map.merge($colors, ('danger': red)) /* 1 */
);

@each $modifier, $value in config.$colors {
  .text-#{$modifier} { color: $value; }
}
```
But this throws this error:

```bash
Error: Undefined variable.
   │
3 │   $colors: map.merge($colors, ('test': blue))
   │                                     ^^^^^^^
   │
  styles/index.scss 3:22  root stylesheet
```
3. So instead I've got to do this:

```scss
// index.scss

@use 'sass:map';
@use 'config' as *; 

$colors: map.merge($colors, ('danger': red));

@each $modifier, $value in config.$colors {
  .text-#{$modifier} { color: $value; }
}
```

I think this could make it a gamer changer for sass library authors and Design Systems.

Thanks in advance.
