### ISSUE TITLE
Use placeholder selectors from other modules

### ISSUE THREAD

**Issue by argv-minus-one** [sass/dart-sass#971]
I've been using `@extend` with placeholder selectors to categorize elements, and apply styles to those categories in various contexts. For example:

```scss
// _categories.scss

h1, h2, h3, h4, h5, h6 {
  @extend %heading;
}

// _homepage.scss

:root.home main %heading {
  // Make all headings in the main content area green,
  // but only on the home page.
  color: green;
}

// main.scss

@import "categories";
@import "homepage";
```

But this won't work with the new module system:

```scss
// _categories.scss

h1, h2, h3, h4, h5, h6 {
  @extend %heading; // Error!
}

// _homepage.scss

@use "categories";

:root.home main %heading { // Matches nothing!
  color: green;
}

// main.scss

@use "homepage";
```

If there were some way to use placeholders (or other `@extend`ed selectors) from other modules, then this pattern could be used with `@use`:

```scss
// _homepage.scss

@use "categories";

:root.home main %(categories.%heading) {
  color: green;
}
```

Headings are a fairly simple example—it's not *too* much effort to just write `h1, h2, h3, h4, h5, h6` in a nested style rule—but it'll get really ugly with some of the other selectors I'm using with this pattern:

```scss
input[type="radio"], input[type="checkbox"] {
	@extend %widget-only-input !optional;
}

input:not([type="color"]):not([type="range"]):not([type="checkbox"]):not(
[type="radio"]):not([type="submit"]):not([type="image"]):not([type="reset"]):not(
[type="button"]):not([type="hidden"]), textarea {
	@extend %text-box-input !optional;
}

button, input:not([type="hidden"]), keygen, meter, output, progress, select,
textarea {
	@extend %form-control !optional;
}

button, input[type="submit"], input[type="reset"], input[type="button"] {
	@extend %form-button !optional;
}
```

**Comment by emilio-martinez** [comment]
If I'm understanding the issue raised correctly, I believe this is addressed in the latest `@extends` documentation: https://sass-lang.com/documentation/at-rules/extend#extension-scope.

That said, it was covered with a bit simpler language in the Sass modules [announcement post](https://sass-lang.com/blog/the-module-system-is-launched):
> If a stylesheet includes @extend, that extension is only applied to stylesheets it imports, not stylesheets that import it.

**Comment by argv-minus-one** [comment]
@emilio-martinez No, you've misunderstood me. I'm well aware that `@extend` is scoped now. I posted this issue because that is too limiting.

Please carefully read this example:

# Input Files

## `_categories.scss`

```scss
h1, h2, h3, h4, h5, h6 {
  @extend %heading;
}
```

## `_homepage.scss`

```scss
@import "categories";

:root.home main %heading {
  color: green;
}
```

# Output

```css
:root.home main h1,
:root.home main h2,
:root.home main h3,
:root.home main h4,
:root.home main h5,
:root.home main h6 {
  color: green;
}
```

Here, `_categories.scss` defines `%heading` as being shorthand for `h1, h2, h3, h4, h5, h6`. Then, `_homepage.scss` imports `_categories.scss`, and has a selector that contains `%heading`. This is good.

But, if the `@import` is changed to `@use`, then this breaks. The definition of `%heading` is not brought in from the other module. As a result, the selector `:root.home main %heading` matches nothing, and the output is empty. This is bad.

I need some way to use this pattern (or something like it) with `@use`.

I hope this is clearer.
