### ISSUE TITLE
wrong :before position

### ISSUE THREAD

**Issue by ahorek** [sass/dart-sass#996]
there's a behavioral difference in a new libsass version and I found out that dart-sass behaves the same way. Is it a bug?

links with https://github.com/sass/libsass/issues/3084

## input.scss

```scss
.red-icon {
  color: #e50026;
}

a.nested:before {
  &.error {
    @extend .red-icon;
  }
}
```

## Actual results

```css
.red-icon, a.nested:before.error {
  color: #e50026; }
```

in this case ```<div class="red-icon">text</div>``` isn't red.

## Expected result

```css
.red-icon, a.nested.error:before {
  color: #e50026; }
```

**Comment by Awjin** [comment]
The parent selector `&` is working as intended. It does not make assumptions about the selector ordering of its parent.

With proper nesting, we can get the correct style:

```
a.nested {
  &:before {}

  &.error:before {}
}
```

**Comment by ahorek** [comment]
https://github.com/sass/libsass/pull/3086

Hi, this is unfortunate. I know there's a workaround, but libsass made this change already, see related PR. So what should we do? Could such attempt become a warning? I would be happy with both approches, but this change caused a silent regression in my codebase ;-(

**Comment by nex3** [comment]
LibSass shouldn't change this in a way that's incompatible with Dart Sass; I've asked LibSass to roll it back in https://github.com/sass/libsass/pull/3086#issuecomment-622657477.

If you want to propose a language change around this behavior, you can follow [the language proposal process](https://github.com/sass/sass/blob/master/CONTRIBUTING.md) to do so.

**Comment by mgreter** [comment]
You are all aware that this basically means the following is not supported by sass?
```scss
A.foo:hover {
  &.other {
    foo: bar;
  }
}
```
I think this should at least produce a warning. And I still fail to see why we can't just ensure
correct output ordering. IMHO it seems the right thing to do to me (with or without warning) ...

**Comment by mgreter** [comment]
Btw. I just checked ruby sass 3.7.4

For input.scss

```scss
.red-icon {
  color: #e50026;
}
a.nested:before {
  &.error {
    @extend .red-icon;
  }
}
```

It did produce correct css

```css
.red-icon, a.nested.error:before {
  color: #e50026; }
```

While for the regular parentization, it also gives invalid css

```css
A.foo:hover.other {
  foo: bar; }
```

So I believe the original bug report by @ahorek is valid!?
